package fr.pontos3.rise.riserest;

import lombok.extern.slf4j.Slf4j;

import java.util.ArrayList;
import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@Slf4j
class LoadDatabase {

    private List<Country> countryList = new ArrayList<Country>();
/*	
	private Country france = new Country().builder().iso2("fr").iso3("fra").isoNumeric(262).
			usualName("France").officialName("France").shortName("France").
			longitude(2.21).latitude(46.22).build();
	
	private Country spain = new Country().builder().iso2("es").iso3("esp").isoNumeric(724).
			usualName("Espagne").officialName("Espagne").shortName("Espagne").
			longitude(-3.74).latitude(40.46).build();
			
*/
    private Country Afghanistan= new Country().builder().iso3("AFG").iso2("AF").isoNumeric(4).usualName("  Afghanistan ").officialName("AFGHANISTAN ").shortName("  Afghanistan ").build();
    private Country AfriqueduSud= new Country().builder().iso3("ZAF").iso2("ZA").isoNumeric(710).usualName("  Afrique du Sud ").officialName("AFRIQUE DU SUD ").shortName("  Afrique du Sud ").build();
    private Country ÎlesÅland= new Country().builder().iso3("ALA").iso2("AX").isoNumeric(248).usualName("  Îles Åland ").officialName("ÅLAND, ÎLES ").shortName("  Îles Åland ").build();
    private Country Albanie= new Country().builder().iso3("ALB").iso2("AL").isoNumeric(8).usualName("  Albanie ").officialName("ALBANIE ").shortName("  Albanie ").build();
    private Country Algérie= new Country().builder().iso3("DZA").iso2("DZ").isoNumeric(12).usualName("Algérie").officialName("ALGÉRIE ").shortName("Algérie").build();
    private Country Allemagne= new Country().builder().iso3("DEU").iso2("DE").isoNumeric(276).usualName("  Allemagne ").officialName("ALLEMAGNE ").shortName("  Allemagne ").build();
    private Country Andorre= new Country().builder().iso3("AND").iso2("AD").isoNumeric(20).usualName("  Andorre ").officialName("ANDORRE ").shortName("  Andorre ").build();
    private Country Angola= new Country().builder().iso3("AGO").iso2("AO").isoNumeric(24).usualName("  Angola ").officialName("ANGOLA ").shortName("  Angola ").build();
    private Country Anguilla= new Country().builder().iso3("AIA").iso2("AI").isoNumeric(660).usualName("  Anguilla ").officialName("ANGUILLA ").shortName("  Anguilla ").build();
    private Country Antarctique= new Country().builder().iso3("ATA").iso2("AQ").isoNumeric(10).usualName("  Antarctique ").officialName("ANTARCTIQUE ").shortName("  Antarctique ").build();
    private Country AntiguaetBarbuda= new Country().builder().iso3("ATG").iso2("AG").isoNumeric(28).usualName("  Antigua-et-Barbuda ").officialName("ANTIGUA-ET-BARBUDA ").shortName("  Antigua-et-Barbuda ").build();
    private Country Arabiesaoudite= new Country().builder().iso3("SAU").iso2("SA").isoNumeric(682).usualName("  Arabie saoudite ").officialName("ARABIE SAOUDITE ").shortName("  Arabie saoudite ").build();
    private Country Argentine= new Country().builder().iso3("ARG").iso2("AR").isoNumeric(32).usualName("  Argentine ").officialName("ARGENTINE ").shortName("  Argentine ").build();
    private Country Arménie= new Country().builder().iso3("ARM").iso2("AM").isoNumeric(51).usualName("  Arménie ").officialName("ARMÉNIE ").shortName("  Arménie ").build();
    private Country Aruba= new Country().builder().iso3("ABW").iso2("AW").isoNumeric(533).usualName("  Aruba ").officialName("ARUBA ").shortName("  Aruba ").build();
    private Country Australie= new Country().builder().iso3("AUS").iso2("AU").isoNumeric(36).usualName("  Australie ").officialName("AUSTRALIE ").shortName("  Australie ").build();
    private Country Autriche= new Country().builder().iso3("AUT").iso2("AT").isoNumeric(40).usualName("  Autriche ").officialName("AUTRICHE ").shortName("  Autriche ").build();
    private Country Azerbaïdjan= new Country().builder().iso3("AZE").iso2("AZ").isoNumeric(31).usualName("  Azerbaïdjan ").officialName("AZERBAÏDJAN ").shortName("  Azerbaïdjan ").build();
    private Country Bahamas= new Country().builder().iso3("BHS").iso2("BS").isoNumeric(44).usualName("  Bahamas ").officialName("BAHAMAS ").shortName("  Bahamas ").build();
    private Country Bahreïn= new Country().builder().iso3("BHR").iso2("BH").isoNumeric(48).usualName("  Bahreïn ").officialName("BAHREÏN ").shortName("  Bahreïn ").build();
    private Country Bangladesh= new Country().builder().iso3("BGD").iso2("BD").isoNumeric(50).usualName("  Bangladesh ").officialName("BANGLADESH ").shortName("  Bangladesh ").build();
    private Country Barbade= new Country().builder().iso3("BRB").iso2("BB").isoNumeric(52).usualName("  Barbade ").officialName("BARBADE ").shortName("  Barbade ").build();
    private Country Biélorussie= new Country().builder().iso3("BLR").iso2("BY").isoNumeric(112).usualName("  Biélorussie ").officialName("BÉLARUS ").shortName("  Biélorussie ").build();
    private Country Belgique= new Country().builder().iso3("BEL").iso2("BE").isoNumeric(56).usualName("  Belgique ").officialName("BELGIQUE ").shortName("  Belgique ").build();
    private Country Belize= new Country().builder().iso3("BLZ").iso2("BZ").isoNumeric(84).usualName("  Belize ").officialName("BELIZE ").shortName("  Belize ").build();
    private Country Bénin= new Country().builder().iso3("BEN").iso2("BJ").isoNumeric(204).usualName("  Bénin ").officialName("BÉNIN ").shortName("  Bénin ").build();
    private Country Bermudes= new Country().builder().iso3("BMU").iso2("BM").isoNumeric(60).usualName("  Bermudes ").officialName("BERMUDES ").shortName("  Bermudes ").build();
    private Country Bhoutan= new Country().builder().iso3("BTN").iso2("BT").isoNumeric(64).usualName("  Bhoutan ").officialName("BHOUTAN ").shortName("  Bhoutan ").build();
    private Country Bolivie= new Country().builder().iso3("BOL").iso2("BO").isoNumeric(68).usualName("  Bolivie ").officialName("BOLIVIE, ÉTAT PLURINATIONAL DE ").shortName("  Bolivie ").build();
    private Country PaysBascaribéens= new Country().builder().iso3("BES").iso2("BQ").isoNumeric(535).usualName("  Pays-Bas caribéens ").officialName("BONAIRE, SAINT-EUSTACHE ET SABA ").shortName("  Pays-Bas caribéens ").build();
    private Country BosnieHerzégovine= new Country().builder().iso3("BIH").iso2("BA").isoNumeric(70).usualName("  Bosnie-Herzégovine ").officialName("BOSNIE-HERZÉGOVINE ").shortName("  Bosnie-Herzégovine ").build();
    private Country Botswana= new Country().builder().iso3("BWA").iso2("BW").isoNumeric(72).usualName("  Botswana ").officialName("BOTSWANA ").shortName("  Botswana ").build();
    private Country ÎleBouvet= new Country().builder().iso3("BVT").iso2("BV").isoNumeric(74).usualName("  Île Bouvet ").officialName("BOUVET, ÎLE ").shortName("  Île Bouvet ").build();
    private Country Brésil= new Country().builder().iso3("BRA").iso2("BR").isoNumeric(76).usualName("  Brésil ").officialName("BRÉSIL ").shortName("  Brésil ").build();
    private Country Brunei= new Country().builder().iso3("BRN").iso2("BN").isoNumeric(96).usualName("  Brunei ").officialName("BRUNÉI DARUSSALAM ").shortName("  Brunei ").build();
    private Country Bulgarie= new Country().builder().iso3("BGR").iso2("BG").isoNumeric(100).usualName("  Bulgarie ").officialName("BULGARIE ").shortName("  Bulgarie ").build();
    private Country BurkinaFaso= new Country().builder().iso3("BFA").iso2("BF").isoNumeric(854).usualName("  Burkina Faso ").officialName("BURKINA FASO ").shortName("  Burkina Faso ").build();
    private Country Burundi= new Country().builder().iso3("BDI").iso2("BI").isoNumeric(108).usualName("  Burundi ").officialName("BURUNDI ").shortName("  Burundi ").build();
    private Country ÎlesCaïmans= new Country().builder().iso3("CYM").iso2("KY").isoNumeric(136).usualName("  Îles Caïmans ").officialName("CAÏMANES, ÎLES ").shortName("  Îles Caïmans ").build();
    private Country Cambodge= new Country().builder().iso3("KHM").iso2("KH").isoNumeric(116).usualName("  Cambodge ").officialName("CAMBODGE ").shortName("  Cambodge ").build();
    private Country Cameroun= new Country().builder().iso3("CMR").iso2("CM").isoNumeric(120).usualName("  Cameroun ").officialName("CAMEROUN ").shortName("  Cameroun ").build();
    private Country Canada= new Country().builder().iso3("CAN").iso2("CA").isoNumeric(124).usualName("  Canada ").officialName("CANADA ").shortName("  Canada ").build();
    private Country CapVert= new Country().builder().iso3("CPV").iso2("CV").isoNumeric(132).usualName("  Cap-Vert ").officialName("CABO VERDE ").shortName("  Cap-Vert ").build();
    private Country Républiquecentrafricaine= new Country().builder().iso3("CAF").iso2("CF").isoNumeric(140).usualName("  République centrafricaine ").officialName("CENTRAFRICAINE, RÉPUBLIQUE ").shortName("  République centrafricaine ").build();
    private Country Chili= new Country().builder().iso3("CHL").iso2("CL").isoNumeric(152).usualName("  Chili ").officialName("CHILI ").shortName("  Chili ").build();
    private Country Chine= new Country().builder().iso3("CHN").iso2("CN").isoNumeric(156).usualName("  Chine ").officialName("CHINE ").shortName("  Chine ").build();
    private Country ÎleChristmas= new Country().builder().iso3("CXR").iso2("CX").isoNumeric(162).usualName("  Île Christmas ").officialName("CHRISTMAS, ÎLE ").shortName("  Île Christmas ").build();
    private Country Chypre= new Country().builder().iso3("CYP").iso2("CY").isoNumeric(196).usualName("  Chypre (pays)").officialName("CHYPRE ").shortName("  Chypre (pays)").build();
    private Country ÎlesCocos= new Country().builder().iso3("CCK").iso2("CC").isoNumeric(166).usualName("  Îles Cocos ").officialName("COCOS (KEELING), ÎLES ").shortName("  Îles Cocos ").build();
    private Country Colombie= new Country().builder().iso3("COL").iso2("CO").isoNumeric(170).usualName("  Colombie ").officialName("COLOMBIE ").shortName("  Colombie ").build();
    private Country Comores= new Country().builder().iso3("COM").iso2("KM").isoNumeric(174).usualName("  Comores (pays) ").officialName("COMORES ").shortName("  Comores (pays) ").build();
    private Country RépubliqueduCongo= new Country().builder().iso3("COG").iso2("CG").isoNumeric(178).usualName("  République du Congo ").officialName("CONGO ").shortName("  République du Congo ").build();
    private Country RépubliquedémocratiqueduCongo= new Country().builder().iso3("COD").iso2("CD").isoNumeric(180).usualName("  République démocratique du Congo ").officialName("CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU ").shortName("  République démocratique du Congo ").build();
    private Country ÎlesCook= new Country().builder().iso3("COK").iso2("CK").isoNumeric(184).usualName("  Îles Cook ").officialName("COOK, ÎLES ").shortName("  Îles Cook ").build();
    private Country CoréeduSud= new Country().builder().iso3("KOR").iso2("KR").isoNumeric(410).usualName("  Corée du Sud ").officialName("CORÉE, RÉPUBLIQUE DE ").shortName("  Corée du Sud ").build();
    private Country CoréeduNord= new Country().builder().iso3("PRK").iso2("KP").isoNumeric(408).usualName("  Corée du Nord ").officialName("CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE ").shortName("  Corée du Nord ").build();
    private Country CostaRica= new Country().builder().iso3("CRI").iso2("CR").isoNumeric(188).usualName("  Costa Rica ").officialName("COSTA RICA ").shortName("  Costa Rica ").build();
    private Country CôtedIvoire= new Country().builder().iso3("CIV").iso2("CI").isoNumeric(384).usualName("  Côte d'Ivoire ").officialName("CÔTE D’IVOIRE ").shortName("  Côte d'Ivoire ").build();
    private Country Croatie= new Country().builder().iso3("HRV").iso2("HR").isoNumeric(191).usualName("  Croatie ").officialName("CROATIE ").shortName("  Croatie ").build();
    private Country Cuba= new Country().builder().iso3("CUB").iso2("CU").isoNumeric(192).usualName("  Cuba ").officialName("CUBA ").shortName("  Cuba ").build();
    private Country Curaçao= new Country().builder().iso3("CUW").iso2("CW").isoNumeric(531).usualName("  Curaçao ").officialName("CURAÇAO ").shortName("  Curaçao ").build();
    private Country Danemark= new Country().builder().iso3("DNK").iso2("DK").isoNumeric(208).usualName("  Danemark ").officialName("DANEMARK ").shortName("  Danemark ").build();
    private Country Djibouti= new Country().builder().iso3("DJI").iso2("DJ").isoNumeric(262).usualName("  Djibouti ").officialName("DJIBOUTI ").shortName("  Djibouti ").build();
    private Country Républiquedominicaine= new Country().builder().iso3("DOM").iso2("DO").isoNumeric(214).usualName("  République dominicaine ").officialName("DOMINICAINE, RÉPUBLIQUE ").shortName("  République dominicaine ").build();
    private Country Dominique= new Country().builder().iso3("DMA").iso2("DM").isoNumeric(212).usualName("  Dominique ").officialName("DOMINIQUE ").shortName("  Dominique ").build();
    private Country Égypte= new Country().builder().iso3("EGY").iso2("EG").isoNumeric(818).usualName("  Égypte ").officialName("ÉGYPTE ").shortName("  Égypte ").build();
    private Country Salvador= new Country().builder().iso3("SLV").iso2("SV").isoNumeric(222).usualName("  Salvador ").officialName("EL SALVADOR ").shortName("  Salvador ").build();
    private Country Émiratsarabesunis= new Country().builder().iso3("ARE").iso2("AE").isoNumeric(784).usualName("  Émirats arabes unis ").officialName("ÉMIRATS ARABES UNIS ").shortName("  Émirats arabes unis ").build();
    private Country Équateur= new Country().builder().iso3("ECU").iso2("EC").isoNumeric(218).usualName("  Équateur (pays) ").officialName("ÉQUATEUR ").shortName("  Équateur (pays) ").build();
    private Country Érythrée= new Country().builder().iso3("ERI").iso2("ER").isoNumeric(232).usualName("  Érythrée ").officialName("ÉRYTHRÉE ").shortName("  Érythrée ").build();
    private Country Espagne= new Country().builder().iso3("ESP").iso2("ES").isoNumeric(724).usualName("  Espagne ").officialName("ESPAGNE ").shortName("  Espagne ").build();
    private Country Estonie= new Country().builder().iso3("EST").iso2("EE").isoNumeric(233).usualName("  Estonie ").officialName("ESTONIE ").shortName("  Estonie ").build();
    private Country ÉtatsUnis= new Country().builder().iso3("USA").iso2("US").isoNumeric(840).usualName("  États-Unis ").officialName("ÉTATS-UNIS ").shortName("  États-Unis ").build();
    private Country Éthiopie= new Country().builder().iso3("ETH").iso2("ET").isoNumeric(231).usualName("  Éthiopie ").officialName("ÉTHIOPIE ").shortName("  Éthiopie ").build();
    private Country Malouines= new Country().builder().iso3("FLK").iso2("FK").isoNumeric(238).usualName("  Malouines ").officialName("FALKLAND, ÎLES (MALVINAS) ").shortName("  Malouines ").build();
    private Country ÎlesFéroé= new Country().builder().iso3("FRO").iso2("FO").isoNumeric(234).usualName("  Îles Féroé ").officialName("FÉROÉ, ÎLES ").shortName("  Îles Féroé ").build();
    private Country Fidji= new Country().builder().iso3("FJI").iso2("FJ").isoNumeric(242).usualName("  Fidji ").officialName("FIDJI ").shortName("  Fidji ").build();
    private Country Finlande= new Country().builder().iso3("FIN").iso2("FI").isoNumeric(246).usualName("  Finlande ").officialName("FINLANDE ").shortName("  Finlande ").build();
    private Country France= new Country().builder().iso3("FRA").iso2("FR").isoNumeric(250).usualName("  France ").officialName("FRANCE ").shortName("  France ").build();
    private Country Gabon= new Country().builder().iso3("GAB").iso2("GA").isoNumeric(266).usualName("  Gabon ").officialName("GABON ").shortName("  Gabon ").build();
    private Country Gambie= new Country().builder().iso3("GMB").iso2("GM").isoNumeric(270).usualName("  Gambie ").officialName("GAMBIE ").shortName("  Gambie ").build();
    private Country Géorgie= new Country().builder().iso3("GEO").iso2("GE").isoNumeric(268).usualName("  Géorgie (pays) ").officialName("GÉORGIE ").shortName("  Géorgie (pays) ").build();
    private Country GéorgieduSudetlesîlesSandwichduSud= new Country().builder().iso3("SGS").iso2("GS").isoNumeric(239).usualName("  Géorgie du Sud-et-les îles Sandwich du Sud ").officialName("GÉORGIE DU SUD ET LES ÎLES SANDWICH DU SUD ").shortName("  Géorgie du Sud-et-les îles Sandwich du Sud ").build();
    private Country Ghana= new Country().builder().iso3("GHA").iso2("GH").isoNumeric(288).usualName("  Ghana ").officialName("GHANA ").shortName("  Ghana ").build();
    private Country Gibraltar= new Country().builder().iso3("GIB").iso2("GI").isoNumeric(292).usualName("  Gibraltar ").officialName("GIBRALTAR ").shortName("  Gibraltar ").build();
    private Country Grèce= new Country().builder().iso3("GRC").iso2("GR").isoNumeric(300).usualName("  Grèce ").officialName("GRÈCE ").shortName("  Grèce ").build();
    private Country Grenade= new Country().builder().iso3("GRD").iso2("GD").isoNumeric(308).usualName("  Grenade (pays)").officialName("GRENADE ").shortName("  Grenade (pays)").build();
    private Country Groenland= new Country().builder().iso3("GRL").iso2("GL").isoNumeric(304).usualName("  Groenland ").officialName("GROENLAND ").shortName("  Groenland ").build();
    private Country Guadeloupe= new Country().builder().iso3("GLP").iso2("GP").isoNumeric(312).usualName("  Guadeloupe ").officialName("GUADELOUPE ").shortName("  Guadeloupe ").build();
    private Country Guam= new Country().builder().iso3("GUM").iso2("GU").isoNumeric(316).usualName("  Guam ").officialName("GUAM ").shortName("  Guam ").build();
    private Country Guatemala= new Country().builder().iso3("GTM").iso2("GT").isoNumeric(320).usualName("  Guatemala ").officialName("GUATEMALA ").shortName("  Guatemala ").build();
    private Country Guernesey= new Country().builder().iso3("GGY").iso2("GG").isoNumeric(831).usualName("  Guernesey ").officialName("GUERNESEY ").shortName("  Guernesey ").build();
    private Country Guinée= new Country().builder().iso3("GIN").iso2("GN").isoNumeric(324).usualName("  Guinée ").officialName("GUINÉE ").shortName("  Guinée ").build();
    private Country GuinéeBissau= new Country().builder().iso3("GNB").iso2("GW").isoNumeric(624).usualName("  Guinée-Bissau ").officialName("GUINÉE-BISSAU ").shortName("  Guinée-Bissau ").build();
    private Country Guinéeéquatoriale= new Country().builder().iso3("GNQ").iso2("GQ").isoNumeric(226).usualName("  Guinée équatoriale ").officialName("GUINÉE ÉQUATORIALE ").shortName("  Guinée équatoriale ").build();
    private Country Guyana= new Country().builder().iso3("GUY").iso2("GY").isoNumeric(328).usualName("  Guyana ").officialName("GUYANA ").shortName("  Guyana ").build();
    private Country Guyane= new Country().builder().iso3("GUF").iso2("GF").isoNumeric(254).usualName("  Guyane ").officialName("GUYANE FRANÇAISE ").shortName("  Guyane ").build();
    private Country Haïti= new Country().builder().iso3("HTI").iso2("HT").isoNumeric(332).usualName("  Haïti ").officialName("HAÏTI ").shortName("  Haïti ").build();
    private Country ÎlesHeardetMacDonald= new Country().builder().iso3("HMD").iso2("HM").isoNumeric(334).usualName("  Îles Heard-et-MacDonald ").officialName("HEARD ET MACDONALD, ÎLES ").shortName("  Îles Heard-et-MacDonald ").build();
    private Country Honduras= new Country().builder().iso3("HND").iso2("HN").isoNumeric(340).usualName("  Honduras ").officialName("HONDURAS ").shortName("  Honduras ").build();
    private Country HongKong= new Country().builder().iso3("HKG").iso2("HK").isoNumeric(344).usualName("  Hong Kong ").officialName("HONG KONG ").shortName("  Hong Kong ").build();
    private Country Hongrie= new Country().builder().iso3("HUN").iso2("HU").isoNumeric(348).usualName("  Hongrie ").officialName("HONGRIE ").shortName("  Hongrie ").build();
    private Country ÎledeMan= new Country().builder().iso3("IMN").iso2("IM").isoNumeric(833).usualName("  Île de Man ").officialName("ÎLE DE MAN ").shortName("  Île de Man ").build();
    private Country ÎlesmineureséloignéesdesÉtatsUnis= new Country().builder().iso3("UMI").iso2("UM").isoNumeric(581).usualName("  Îles mineures éloignées des États-Unis ").officialName("ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS ").shortName("  Îles mineures éloignées des États-Unis ").build();
    private Country ÎlesViergesbritanniques= new Country().builder().iso3("VGB").iso2("VG").isoNumeric(92).usualName("  Îles Vierges britanniques ").officialName("ÎLES VIERGES BRITANNIQUES ").shortName("  Îles Vierges britanniques ").build();
    private Country ÎlesViergesdesÉtatsUnis= new Country().builder().iso3("VIR").iso2("VI").isoNumeric(850).usualName("  Îles Vierges des États-Unis ").officialName("ÎLES VIERGES DES ÉTATS-UNIS ").shortName("  Îles Vierges des États-Unis ").build();
    private Country Inde= new Country().builder().iso3("IND").iso2("IN").isoNumeric(356).usualName("  Inde ").officialName("INDE ").shortName("  Inde ").build();
    private Country Indonésie= new Country().builder().iso3("IDN").iso2("ID").isoNumeric(360).usualName("  Indonésie ").officialName("INDONÉSIE ").shortName("  Indonésie ").build();
    private Country Iran= new Country().builder().iso3("IRN").iso2("IR").isoNumeric(364).usualName("  Iran ").officialName("IRAN, RÉPUBLIQUE ISLAMIQUE D' ").shortName("  Iran ").build();
    private Country Irak= new Country().builder().iso3("IRQ").iso2("IQ").isoNumeric(368).usualName("  Irak ").officialName("IRAQ ").shortName("  Irak ").build();
    private Country Irlande= new Country().builder().iso3("IRL").iso2("IE").isoNumeric(372).usualName("  Irlande (pays)").officialName("IRLANDE ").shortName("  Irlande (pays)").build();
    private Country Islande= new Country().builder().iso3("ISL").iso2("IS").isoNumeric(352).usualName("  Islande ").officialName("ISLANDE ").shortName("  Islande ").build();
    private Country Israël= new Country().builder().iso3("ISR").iso2("IL").isoNumeric(376).usualName("  Israël ").officialName("ISRAËL ").shortName("  Israël ").build();
    private Country Italie= new Country().builder().iso3("ITA").iso2("IT").isoNumeric(380).usualName("  Italie ").officialName("ITALIE ").shortName("  Italie ").build();
    private Country Jamaïque= new Country().builder().iso3("JAM").iso2("JM").isoNumeric(388).usualName("  Jamaïque ").officialName("JAMAÏQUE ").shortName("  Jamaïque ").build();
    private Country Japon= new Country().builder().iso3("JPN").iso2("JP").isoNumeric(392).usualName("  Japon ").officialName("JAPON ").shortName("  Japon ").build();
    private Country Jersey= new Country().builder().iso3("JEY").iso2("JE").isoNumeric(832).usualName("  Jersey ").officialName("JERSEY ").shortName("  Jersey ").build();
    private Country Jordanie= new Country().builder().iso3("JOR").iso2("JO").isoNumeric(400).usualName("  Jordanie ").officialName("JORDANIE ").shortName("  Jordanie ").build();
    private Country Kazakhstan= new Country().builder().iso3("KAZ").iso2("KZ").isoNumeric(398).usualName("  Kazakhstan ").officialName("KAZAKHSTAN ").shortName("  Kazakhstan ").build();
    private Country Kenya= new Country().builder().iso3("KEN").iso2("KE").isoNumeric(404).usualName("  Kenya ").officialName("KENYA ").shortName("  Kenya ").build();
    private Country Kirghizistan= new Country().builder().iso3("KGZ").iso2("KG").isoNumeric(417).usualName("  Kirghizistan ").officialName("KIRGHIZISTAN ").shortName("  Kirghizistan ").build();
    private Country Kiribati= new Country().builder().iso3("KIR").iso2("KI").isoNumeric(296).usualName("  Kiribati ").officialName("KIRIBATI ").shortName("  Kiribati ").build();
    private Country Koweït= new Country().builder().iso3("KWT").iso2("KW").isoNumeric(414).usualName("  Koweït ").officialName("KOWEÏT ").shortName("  Koweït ").build();
    private Country Laos= new Country().builder().iso3("LAO").iso2("LA").isoNumeric(418).usualName("  Laos ").officialName("LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE ").shortName("  Laos ").build();
    private Country Lesotho= new Country().builder().iso3("LSO").iso2("LS").isoNumeric(426).usualName("  Lesotho ").officialName("LESOTHO ").shortName("  Lesotho ").build();
    private Country Lettonie= new Country().builder().iso3("LVA").iso2("LV").isoNumeric(428).usualName("  Lettonie ").officialName("LETTONIE ").shortName("  Lettonie ").build();
    private Country Liban= new Country().builder().iso3("LBN").iso2("LB").isoNumeric(422).usualName("  Liban ").officialName("LIBAN ").shortName("  Liban ").build();
    private Country Liberia= new Country().builder().iso3("LBR").iso2("LR").isoNumeric(430).usualName("  Liberia ").officialName("LIBÉRIA ").shortName("  Liberia ").build();
    private Country Libye= new Country().builder().iso3("LBY").iso2("LY").isoNumeric(434).usualName("  Libye ").officialName("LIBYE ").shortName("  Libye ").build();
    private Country Liechtenstein= new Country().builder().iso3("LIE").iso2("LI").isoNumeric(438).usualName("  Liechtenstein ").officialName("LIECHTENSTEIN ").shortName("  Liechtenstein ").build();
    private Country Lituanie= new Country().builder().iso3("LTU").iso2("LT").isoNumeric(440).usualName("  Lituanie ").officialName("LITUANIE ").shortName("  Lituanie ").build();
    private Country Luxembourg= new Country().builder().iso3("LUX").iso2("LU").isoNumeric(442).usualName("  Luxembourg (pays) ").officialName("LUXEMBOURG ").shortName("  Luxembourg (pays) ").build();
    private Country Macao= new Country().builder().iso3("MAC").iso2("MO").isoNumeric(446).usualName("  Macao ").officialName("MACAO ").shortName("  Macao ").build();
    private Country MacédoineduNord= new Country().builder().iso3("MKD").iso2("MK").isoNumeric(807).usualName("  Macédoine du Nord ").officialName("RÉPUBLIQUE DE MACÉDOINE ").shortName("  Macédoine du Nord ").build();
    private Country Madagascar= new Country().builder().iso3("MDG").iso2("MG").isoNumeric(450).usualName("  Madagascar ").officialName("MADAGASCAR ").shortName("  Madagascar ").build();
    private Country Malaisie= new Country().builder().iso3("MYS").iso2("MY").isoNumeric(458).usualName("  Malaisie ").officialName("MALAISIE ").shortName("  Malaisie ").build();
    private Country Malawi= new Country().builder().iso3("MWI").iso2("MW").isoNumeric(454).usualName("  Malawi ").officialName("MALAWI ").shortName("  Malawi ").build();
    private Country Maldives= new Country().builder().iso3("MDV").iso2("MV").isoNumeric(462).usualName("  Maldives ").officialName("MALDIVES ").shortName("  Maldives ").build();
    private Country Mali= new Country().builder().iso3("MLI").iso2("ML").isoNumeric(466).usualName("  Mali ").officialName("MALI ").shortName("  Mali ").build();
    private Country Malte= new Country().builder().iso3("MLT").iso2("MT").isoNumeric(470).usualName("  Malte ").officialName("MALTE ").shortName("  Malte ").build();
    private Country ÎlesMariannesduNord= new Country().builder().iso3("MNP").iso2("MP").isoNumeric(580).usualName("  Îles Mariannes du Nord ").officialName("MARIANNES DU NORD, ÎLES ").shortName("  Îles Mariannes du Nord ").build();
    private Country Maroc= new Country().builder().iso3("MAR").iso2("MA").isoNumeric(504).usualName("  Maroc ").officialName("MAROC ").shortName("  Maroc ").build();
    private Country ÎlesMarshall= new Country().builder().iso3("MHL").iso2("MH").isoNumeric(584).usualName("  Îles Marshall (pays) ").officialName("MARSHALL, ÎLES ").shortName("  Îles Marshall (pays) ").build();
    private Country Martinique= new Country().builder().iso3("MTQ").iso2("MQ").isoNumeric(474).usualName("  Martinique ").officialName("MARTINIQUE ").shortName("  Martinique ").build();
    private Country Maurice= new Country().builder().iso3("MUS").iso2("MU").isoNumeric(480).usualName("  Maurice (pays) ").officialName("MAURICE ").shortName("  Maurice (pays) ").build();
    private Country Mauritanie= new Country().builder().iso3("MRT").iso2("MR").isoNumeric(478).usualName("  Mauritanie ").officialName("MAURITANIE ").shortName("  Mauritanie ").build();
    private Country Mayotte= new Country().builder().iso3("MYT").iso2("YT").isoNumeric(175).usualName("  Mayotte ").officialName("MAYOTTE ").shortName("  Mayotte ").build();
    private Country Mexique= new Country().builder().iso3("MEX").iso2("MX").isoNumeric(484).usualName("  Mexique ").officialName("MEXIQUE ").shortName("  Mexique ").build();
    private Country ÉtatsfédérésdeMicronésie= new Country().builder().iso3("FSM").iso2("FM").isoNumeric(583).usualName("  États fédérés de Micronésie (pays) ").officialName("MICRONÉSIE, ÉTATS FÉDÉRÉS DE ").shortName("  États fédérés de Micronésie (pays) ").build();
    private Country Moldavie= new Country().builder().iso3("MDA").iso2("MD").isoNumeric(498).usualName("  Moldavie ").officialName("MOLDAVIE ").shortName("  Moldavie ").build();
    private Country Monaco= new Country().builder().iso3("MCO").iso2("MC").isoNumeric(492).usualName("  Monaco ").officialName("MONACO ").shortName("  Monaco ").build();
    private Country Mongolie= new Country().builder().iso3("MNG").iso2("MN").isoNumeric(496).usualName("  Mongolie ").officialName("MONGOLIE ").shortName("  Mongolie ").build();
    private Country Monténégro= new Country().builder().iso3("MNE").iso2("ME").isoNumeric(499).usualName("  Monténégro ").officialName("MONTÉNÉGRO ").shortName("  Monténégro ").build();
    private Country Montserrat= new Country().builder().iso3("MSR").iso2("MS").isoNumeric(500).usualName("  Montserrat ").officialName("MONTSERRAT ").shortName("  Montserrat ").build();
    private Country Mozambique= new Country().builder().iso3("MOZ").iso2("MZ").isoNumeric(508).usualName("  Mozambique ").officialName("MOZAMBIQUE ").shortName("  Mozambique ").build();
    private Country Birmanie= new Country().builder().iso3("MMR").iso2("MM").isoNumeric(104).usualName("  Birmanie ").officialName("MYANMAR ").shortName("  Birmanie ").build();
    private Country Namibie= new Country().builder().iso3("NAM").iso2("NA").isoNumeric(516).usualName("  Namibie ").officialName("NAMIBIE ").shortName("  Namibie ").build();
    private Country Nauru= new Country().builder().iso3("NRU").iso2("NR").isoNumeric(520).usualName("  Nauru ").officialName("NAURU ").shortName("  Nauru ").build();
    private Country Népal= new Country().builder().iso3("NPL").iso2("NP").isoNumeric(524).usualName("  Népal ").officialName("NÉPAL ").shortName("  Népal ").build();
    private Country Nicaragua= new Country().builder().iso3("NIC").iso2("NI").isoNumeric(558).usualName("  Nicaragua ").officialName("NICARAGUA ").shortName("  Nicaragua ").build();
    private Country Niger= new Country().builder().iso3("NER").iso2("NE").isoNumeric(562).usualName("  Niger ").officialName("NIGER ").shortName("  Niger ").build();
    private Country Nigeria= new Country().builder().iso3("NGA").iso2("NG").isoNumeric(566).usualName("  Nigeria ").officialName("NIGÉRIA ").shortName("  Nigeria ").build();
    private Country Niue= new Country().builder().iso3("NIU").iso2("NU").isoNumeric(570).usualName("  Niue ").officialName("NIUÉ ").shortName("  Niue ").build();
    private Country ÎleNorfolk= new Country().builder().iso3("NFK").iso2("NF").isoNumeric(574).usualName("  Île Norfolk ").officialName("NORFOLK, ÎLE ").shortName("  Île Norfolk ").build();
    private Country Norvège= new Country().builder().iso3("NOR").iso2("NO").isoNumeric(578).usualName("  Norvège ").officialName("NORVÈGE ").shortName("  Norvège ").build();
    private Country NouvelleCalédonie= new Country().builder().iso3("NCL").iso2("NC").isoNumeric(540).usualName("  Nouvelle-Calédonie ").officialName("NOUVELLE-CALÉDONIE ").shortName("  Nouvelle-Calédonie ").build();
    private Country NouvelleZélande= new Country().builder().iso3("NZL").iso2("NZ").isoNumeric(554).usualName("  Nouvelle-Zélande ").officialName("NOUVELLE-ZÉLANDE ").shortName("  Nouvelle-Zélande ").build();
    private Country TerritoirebritanniquedelocéanIndien= new Country().builder().iso3("IOT").iso2("IO").isoNumeric(86).usualName("  Territoire britannique de l'océan Indien ").officialName("OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L' ").shortName("  Territoire britannique de l'océan Indien ").build();
    private Country Oman= new Country().builder().iso3("OMN").iso2("OM").isoNumeric(512).usualName("  Oman ").officialName("OMAN ").shortName("  Oman ").build();
    private Country Ouganda= new Country().builder().iso3("UGA").iso2("UG").isoNumeric(800).usualName("  Ouganda ").officialName("OUGANDA ").shortName("  Ouganda ").build();
    private Country Ouzbékistan= new Country().builder().iso3("UZB").iso2("UZ").isoNumeric(860).usualName("  Ouzbékistan ").officialName("OUZBÉKISTAN ").shortName("  Ouzbékistan ").build();
    private Country Pakistan= new Country().builder().iso3("PAK").iso2("PK").isoNumeric(586).usualName("  Pakistan ").officialName("PAKISTAN ").shortName("  Pakistan ").build();
    private Country Palaos= new Country().builder().iso3("PLW").iso2("PW").isoNumeric(585).usualName("  Palaos ").officialName("PALAOS ").shortName("  Palaos ").build();
    private Country Palestine= new Country().builder().iso3("PSE").iso2("PS").isoNumeric(275).usualName("  Palestine ").officialName("ÉTAT DE PALESTINE ").shortName("  Palestine ").build();
    private Country Panama= new Country().builder().iso3("PAN").iso2("PA").isoNumeric(591).usualName("  Panama ").officialName("PANAMA ").shortName("  Panama ").build();
    private Country PapouasieNouvelleGuinée= new Country().builder().iso3("PNG").iso2("PG").isoNumeric(598).usualName("  Papouasie-Nouvelle-Guinée ").officialName("PAPOUASIE-NOUVELLE-GUINÉE ").shortName("  Papouasie-Nouvelle-Guinée ").build();
    private Country Paraguay= new Country().builder().iso3("PRY").iso2("PY").isoNumeric(600).usualName("  Paraguay ").officialName("PARAGUAY ").shortName("  Paraguay ").build();
    private Country PaysBas= new Country().builder().iso3("NLD").iso2("NL").isoNumeric(528).usualName("  Pays-Bas ").officialName("PAYS-BAS ").shortName("  Pays-Bas ").build();
    private Country Pérou= new Country().builder().iso3("PER").iso2("PE").isoNumeric(604).usualName("  Pérou ").officialName("PÉROU ").shortName("  Pérou ").build();
    private Country Philippines= new Country().builder().iso3("PHL").iso2("PH").isoNumeric(608).usualName("  Philippines ").officialName("PHILIPPINES ").shortName("  Philippines ").build();
    private Country ÎlesPitcairn= new Country().builder().iso3("PCN").iso2("PN").isoNumeric(612).usualName("  Îles Pitcairn ").officialName("PITCAIRN ").shortName("  Îles Pitcairn ").build();
    private Country Pologne= new Country().builder().iso3("POL").iso2("PL").isoNumeric(616).usualName("  Pologne ").officialName("POLOGNE ").shortName("  Pologne ").build();
    private Country Polynésiefrançaise= new Country().builder().iso3("PYF").iso2("PF").isoNumeric(258).usualName("  Polynésie française ").officialName("POLYNÉSIE FRANÇAISE ").shortName("  Polynésie française ").build();
    private Country PortoRico= new Country().builder().iso3("PRI").iso2("PR").isoNumeric(630).usualName("  Porto Rico ").officialName("PORTO RICO ").shortName("  Porto Rico ").build();
    private Country Portugal= new Country().builder().iso3("PRT").iso2("PT").isoNumeric(620).usualName("  Portugal ").officialName("PORTUGAL ").shortName("  Portugal ").build();
    private Country Qatar= new Country().builder().iso3("QAT").iso2("QA").isoNumeric(634).usualName("  Qatar ").officialName("QATAR ").shortName("  Qatar ").build();
    private Country LaRéunion= new Country().builder().iso3("REU").iso2("RE").isoNumeric(638).usualName("  La Réunion ").officialName("RÉUNION ").shortName("  La Réunion ").build();
    private Country Roumanie= new Country().builder().iso3("ROU").iso2("RO").isoNumeric(642).usualName("  Roumanie ").officialName("ROUMANIE ").shortName("  Roumanie ").build();
    private Country RoyaumeUni= new Country().builder().iso3("GBR").iso2("GB").isoNumeric(826).usualName("  Royaume-Uni ").officialName("ROYAUME-UNI ").shortName("  Royaume-Uni ").build();
    private Country Russie= new Country().builder().iso3("RUS").iso2("RU").isoNumeric(643).usualName("  Russie ").officialName("RUSSIE, FÉDÉRATION DE ").shortName("  Russie ").build();
    private Country Rwanda= new Country().builder().iso3("RWA").iso2("RW").isoNumeric(646).usualName("  Rwanda ").officialName("RWANDA ").shortName("  Rwanda ").build();
    private Country Républiquearabesahraouiedémocratique= new Country().builder().iso3("ESH").iso2("EH").isoNumeric(732).usualName("  République arabe sahraouie démocratique ").officialName("SAHARA OCCIDENTAL ").shortName("  République arabe sahraouie démocratique ").build();
    private Country SaintBarthélemy= new Country().builder().iso3("BLM").iso2("BL").isoNumeric(652).usualName("  Saint-Barthélemy ").officialName("SAINT-BARTHÉLEMY ").shortName("  Saint-Barthélemy ").build();
    private Country SaintChristopheetNiévès= new Country().builder().iso3("KNA").iso2("KN").isoNumeric(659).usualName("  Saint-Christophe-et-Niévès ").officialName("SAINT-KITTS-ET-NEVIS ").shortName("  Saint-Christophe-et-Niévès ").build();
    private Country SaintMarin= new Country().builder().iso3("SMR").iso2("SM").isoNumeric(674).usualName("  Saint-Marin ").officialName("SAINT-MARIN ").shortName("  Saint-Marin ").build();
    private Country SaintMartinFr= new Country().builder().iso3("MAF").iso2("MF").isoNumeric(663).usualName("  Saint-Martin ").officialName("SAINT-MARTIN (PARTIE FRANÇAISE) ").shortName("  Saint-Martin ").build();
    private Country SaintMartinNl= new Country().builder().iso3("SXM").iso2("SX").isoNumeric(534).usualName("  Saint-Martin ").officialName("SAINT-MARTIN (PARTIE NÉERLANDAISE) ").shortName("  Saint-Martin ").build();
    private Country SaintPierreetMiquelon= new Country().builder().iso3("SPM").iso2("PM").isoNumeric(666).usualName("  Saint-Pierre-et-Miquelon ").officialName("SAINT-PIERRE-ET-MIQUELON ").shortName("  Saint-Pierre-et-Miquelon ").build();
    private Country SaintSiège= new Country().builder().iso3("VAT").iso2("VA").isoNumeric(336).usualName("  Saint-Siège (État de la Cité du Vatican) ").officialName("SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN) ").shortName("  Saint-Siège (État de la Cité du Vatican) ").build();
    private Country SaintVincentetlesGrenadines= new Country().builder().iso3("VCT").iso2("VC").isoNumeric(670).usualName("  Saint-Vincent-et-les-Grenadines ").officialName("SAINT-VINCENT-ET-LES-GRENADINES ").shortName("  Saint-Vincent-et-les-Grenadines ").build();
    private Country SainteHélène= new Country().builder().iso3("SHN").iso2("SH").isoNumeric(654).usualName("  Sainte-Hélène, Ascension et Tristan da Cunha ").officialName("SAINTE-HÉLÈNE, ASCENSION ET TRISTAN DA CUNHA ").shortName("  Sainte-Hélène, Ascension et Tristan da Cunha ").build();
    private Country SainteLucie= new Country().builder().iso3("LCA").iso2("LC").isoNumeric(662).usualName("  Sainte-Lucie ").officialName("SAINTE-LUCIE ").shortName("  Sainte-Lucie ").build();
    private Country Salomon= new Country().builder().iso3("SLB").iso2("SB").isoNumeric(90).usualName("  Salomon ").officialName("SALOMON, ÎLES ").shortName("  Salomon ").build();
    private Country Samoa= new Country().builder().iso3("WSM").iso2("WS").isoNumeric(882).usualName("  Samoa ").officialName("SAMOA ").shortName("  Samoa ").build();
    private Country Samoaaméricaines= new Country().builder().iso3("ASM").iso2("AS").isoNumeric(16).usualName("  Samoa américaines ").officialName("SAMOA AMÉRICAINES ").shortName("  Samoa américaines ").build();
    private Country SaoToméetPrincipe= new Country().builder().iso3("STP").iso2("ST").isoNumeric(678).usualName("  Sao Tomé-et-Principe ").officialName("SAO TOMÉ-ET-PRINCIPE ").shortName("  Sao Tomé-et-Principe ").build();
    private Country Sénégal= new Country().builder().iso3("SEN").iso2("SN").isoNumeric(686).usualName("  Sénégal ").officialName("SÉNÉGAL ").shortName("  Sénégal ").build();
    private Country Serbie= new Country().builder().iso3("SRB").iso2("RS").isoNumeric(688).usualName("  Serbie ").officialName("SERBIE ").shortName("  Serbie ").build();
    private Country Seychelles= new Country().builder().iso3("SYC").iso2("SC").isoNumeric(690).usualName("  Seychelles ").officialName("SEYCHELLES ").shortName("  Seychelles ").build();
    private Country SierraLeone= new Country().builder().iso3("SLE").iso2("SL").isoNumeric(694).usualName("  Sierra Leone ").officialName("SIERRA LEONE ").shortName("  Sierra Leone ").build();
    private Country Singapour= new Country().builder().iso3("SGP").iso2("SG").isoNumeric(702).usualName("  Singapour ").officialName("SINGAPOUR ").shortName("  Singapour ").build();
    private Country Slovaquie= new Country().builder().iso3("SVK").iso2("SK").isoNumeric(703).usualName("  Slovaquie ").officialName("SLOVAQUIE ").shortName("  Slovaquie ").build();
    private Country Slovénie= new Country().builder().iso3("SVN").iso2("SI").isoNumeric(705).usualName("  Slovénie ").officialName("SLOVÉNIE ").shortName("  Slovénie ").build();
    private Country Somalie= new Country().builder().iso3("SOM").iso2("SO").isoNumeric(706).usualName("  Somalie ").officialName("SOMALIE ").shortName("  Somalie ").build();
    private Country Soudan= new Country().builder().iso3("SDN").iso2("SD").isoNumeric(729).usualName("  Soudan ").officialName("SOUDAN ").shortName("  Soudan ").build();
    private Country SoudanduSud= new Country().builder().iso3("SSD").iso2("SS").isoNumeric(728).usualName("  Soudan du Sud ").officialName("SOUDAN DU SUD ").shortName("  Soudan du Sud ").build();
    private Country SriLanka= new Country().builder().iso3("LKA").iso2("LK").isoNumeric(144).usualName("  Sri Lanka ").officialName("SRI LANKA ").shortName("  Sri Lanka ").build();
    private Country Suède= new Country().builder().iso3("SWE").iso2("SE").isoNumeric(752).usualName("  Suède ").officialName("SUÈDE ").shortName("  Suède ").build();
    private Country Suisse= new Country().builder().iso3("CHE").iso2("CH").isoNumeric(756).usualName("  Suisse ").officialName("SUISSE ").shortName("  Suisse ").build();
    private Country Suriname= new Country().builder().iso3("SUR").iso2("SR").isoNumeric(740).usualName("  Suriname ").officialName("SURINAME ").shortName("  Suriname ").build();
    private Country SvalbardetileJanMayen= new Country().builder().iso3("SJM").iso2("SJ").isoNumeric(744).usualName("  Svalbard et ile Jan Mayen ").officialName("SVALBARD ET ÎLE JAN MAYEN ").shortName("  Svalbard et ile Jan Mayen ").build();
    private Country Swaziland= new Country().builder().iso3("SWZ").iso2("SZ").isoNumeric(748).usualName("  Swaziland ").officialName("ESWATINI ").shortName("  Swaziland ").build();
    private Country Syrie= new Country().builder().iso3("SYR").iso2("SY").isoNumeric(760).usualName("  Syrie ").officialName("SYRIENNE, RÉPUBLIQUE ARABE ").shortName("  Syrie ").build();
    private Country Tadjikistan= new Country().builder().iso3("TJK").iso2("TJ").isoNumeric(762).usualName("  Tadjikistan ").officialName("TADJIKISTAN ").shortName("  Tadjikistan ").build();
    private Country Taïwan= new Country().builder().iso3("TWN").iso2("TW").isoNumeric(158).usualName("  Taïwan / (République de Chine (Taïwan)) ").officialName("TAÏWAN, PROVINCE DE CHINE ").shortName("  Taïwan / (République de Chine (Taïwan)) ").build();
    private Country Tanzanie= new Country().builder().iso3("TZA").iso2("TZ").isoNumeric(834).usualName("  Tanzanie ").officialName("TANZANIE, RÉPUBLIQUE UNIE DE ").shortName("  Tanzanie ").build();
    private Country Tchad= new Country().builder().iso3("TCD").iso2("TD").isoNumeric(148).usualName("  Tchad ").officialName("TCHAD ").shortName("  Tchad ").build();
    private Country Tchéquie= new Country().builder().iso3("CZE").iso2("CZ").isoNumeric(203).usualName("  Tchéquie ").officialName("TCHÉQUIE ").shortName("  Tchéquie ").build();
    private Country Terresaustralesetantarctiquesfrançaises= new Country().builder().iso3("ATF").iso2("TF").isoNumeric(260).usualName("  Terres australes et antarctiques françaises ").officialName("TERRES AUSTRALES FRANÇAISES ").shortName("  Terres australes et antarctiques françaises ").build();
    private Country Thaïlande= new Country().builder().iso3("THA").iso2("TH").isoNumeric(764).usualName("  Thaïlande ").officialName("THAÏLANDE ").shortName("  Thaïlande ").build();
    private Country Timororiental= new Country().builder().iso3("TLS").iso2("TL").isoNumeric(626).usualName("  Timor oriental ").officialName("TIMOR-LESTE ").shortName("  Timor oriental ").build();
    private Country Togo= new Country().builder().iso3("TGO").iso2("TG").isoNumeric(768).usualName("  Togo ").officialName("TOGO ").shortName("  Togo ").build();
    private Country Tokelau= new Country().builder().iso3("TKL").iso2("TK").isoNumeric(772).usualName("  Tokelau ").officialName("TOKELAU ").shortName("  Tokelau ").build();
    private Country Tonga= new Country().builder().iso3("TON").iso2("TO").isoNumeric(776).usualName("  Tonga ").officialName("TONGA ").shortName("  Tonga ").build();
    private Country TrinitéetTobago= new Country().builder().iso3("TTO").iso2("TT").isoNumeric(780).usualName("  Trinité-et-Tobago ").officialName("TRINITÉ-ET-TOBAGO ").shortName("  Trinité-et-Tobago ").build();
    private Country Tunisie= new Country().builder().iso3("TUN").iso2("TN").isoNumeric(788).usualName("  Tunisie ").officialName("TUNISIE ").shortName("  Tunisie ").build();
    private Country Turkménistan= new Country().builder().iso3("TKM").iso2("TM").isoNumeric(795).usualName("  Turkménistan ").officialName("TURKMÉNISTAN ").shortName("  Turkménistan ").build();
    private Country ÎlesTurquesetCaïques= new Country().builder().iso3("TCA").iso2("TC").isoNumeric(796).usualName("  Îles Turques-et-Caïques ").officialName("TURKS ET CAÏQUES, ÎLES ").shortName("  Îles Turques-et-Caïques ").build();
    private Country Turquie= new Country().builder().iso3("TUR").iso2("TR").isoNumeric(792).usualName("  Turquie ").officialName("TURQUIE ").shortName("  Turquie ").build();
    private Country Tuvalu= new Country().builder().iso3("TUV").iso2("TV").isoNumeric(798).usualName("  Tuvalu ").officialName("TUVALU ").shortName("  Tuvalu ").build();
    private Country Ukraine= new Country().builder().iso3("UKR").iso2("UA").isoNumeric(804).usualName("  Ukraine ").officialName("UKRAINE ").shortName("  Ukraine ").build();
    private Country Uruguay= new Country().builder().iso3("URY").iso2("UY").isoNumeric(858).usualName("  Uruguay ").officialName("URUGUAY ").shortName("  Uruguay ").build();
    private Country Vanuatu= new Country().builder().iso3("VUT").iso2("VU").isoNumeric(548).usualName("  Vanuatu ").officialName("VANUATU ").shortName("  Vanuatu ").build();
    private Country Venezuela= new Country().builder().iso3("VEN").iso2("VE").isoNumeric(862).usualName("  Venezuela ").officialName("VENEZUELA, RÉPUBLIQUE BOLIVARIENNE DU ").shortName("  Venezuela ").build();
    private Country ViêtNam= new Country().builder().iso3("VNM").iso2("VN").isoNumeric(704).usualName("  Viêt Nam ").officialName("VIET NAM ").shortName("  Viêt Nam ").build();
    private Country WallisetFutuna= new Country().builder().iso3("WLF").iso2("WF").isoNumeric(876).usualName("  Wallis-et-Futuna ").officialName("WALLIS-ET-FUTUNA ").shortName("  Wallis-et-Futuna ").build();
    private Country Yémen= new Country().builder().iso3("YEM").iso2("YE").isoNumeric(887).usualName("  Yémen ").officialName("YÉMEN ").shortName("  Yémen ").build();
    private Country Zambie= new Country().builder().iso3("ZMB").iso2("ZM").isoNumeric(894).usualName("  Zambie ").officialName("ZAMBIE ").shortName("  Zambie ").build();
    private Country Zimbabwe= new Country().builder().iso3("ZWE").iso2("ZW").isoNumeric(716).usualName("  Zimbabwe ").officialName("ZIMBABWE ").shortName("  Zimbabwe ").build();

  @Bean
  CommandLineRunner initDatabaseCountry(CountryRepository countryRepository, AreaRepository repository) {
    return args -> {
  	
    	countryRepository.save(Afghanistan);
    	countryRepository.save(AfriqueduSud);
    	countryRepository.save(ÎlesÅland);
    	countryRepository.save(Albanie);
    	countryRepository.save(Algérie);
    	countryRepository.save(Allemagne);
    	countryRepository.save(Andorre);
    	countryRepository.save(Angola);
    	countryRepository.save(Anguilla);
    	countryRepository.save(Antarctique);
    	countryRepository.save(AntiguaetBarbuda);
    	countryRepository.save(Arabiesaoudite);
    	countryRepository.save(Argentine);
    	countryRepository.save(Arménie);
    	countryRepository.save(Aruba);
    	countryRepository.save(Australie);
    	countryRepository.save(Autriche);
    	countryRepository.save(Azerbaïdjan);
    	countryRepository.save(Bahamas);
    	countryRepository.save(Bahreïn);
    	countryRepository.save(Bangladesh);
    	countryRepository.save(Barbade);
    	countryRepository.save(Biélorussie); //étape 1
    	countryRepository.save(Belgique);
    	countryRepository.save(Belize);
    	countryRepository.save(Bénin);
    	countryRepository.save(Bermudes);
    	countryRepository.save(Bhoutan);
    	countryRepository.save(Bolivie);
    	countryRepository.save(PaysBascaribéens);
    	countryRepository.save(BosnieHerzégovine);
    	countryRepository.save(Botswana);
    	countryRepository.save(ÎleBouvet);
    	countryRepository.save(Brésil);
    	countryRepository.save(Brunei);
    	countryRepository.save(Bulgarie);
    	countryRepository.save(BurkinaFaso);
    	countryRepository.save(Burundi);
    	countryRepository.save(ÎlesCaïmans);
    	countryRepository.save(Cambodge);
    	countryRepository.save(Cameroun);
    	countryRepository.save(Canada);
    	countryRepository.save(CapVert);
    	countryRepository.save(Républiquecentrafricaine);
    	countryRepository.save(Chili); 
    	countryRepository.save(Chine);
    	countryRepository.save(ÎleChristmas);
    	countryRepository.save(Chypre);
    	countryRepository.save(ÎlesCocos);
    	countryRepository.save(Colombie);
    	countryRepository.save(Comores);
    	countryRepository.save(RépubliqueduCongo);
    	countryRepository.save(RépubliquedémocratiqueduCongo);
    	countryRepository.save(ÎlesCook);
    	countryRepository.save(CoréeduSud);
    	countryRepository.save(CoréeduNord);
    	countryRepository.save(CostaRica);
    	countryRepository.save(CôtedIvoire);
    	countryRepository.save(Croatie);
    	countryRepository.save(Cuba);
    	countryRepository.save(Curaçao);
    	countryRepository.save(Danemark);
    	countryRepository.save(Djibouti);
    	countryRepository.save(Républiquedominicaine);
    	countryRepository.save(Dominique);
    	countryRepository.save(Égypte);
    	countryRepository.save(Salvador);
    	countryRepository.save(Émiratsarabesunis);
    	countryRepository.save(Équateur);
    	countryRepository.save(Érythrée);
    	countryRepository.save(Espagne);
    	countryRepository.save(Estonie);
    	countryRepository.save(ÉtatsUnis);
    	countryRepository.save(Éthiopie);
    	countryRepository.save(Malouines);
    	countryRepository.save(ÎlesFéroé);
    	countryRepository.save(Fidji);
    	countryRepository.save(Finlande);
    	countryRepository.save(France);
    	countryRepository.save(Gabon);
    	countryRepository.save(Gambie);
    	countryRepository.save(Géorgie);
    	countryRepository.save(GéorgieduSudetlesîlesSandwichduSud);
    	countryRepository.save(Ghana);
    	countryRepository.save(Gibraltar);
    	countryRepository.save(Grèce);
    	countryRepository.save(Grenade);
    	countryRepository.save(Groenland);
    	countryRepository.save(Guadeloupe);
    	countryRepository.save(Guam);
    	countryRepository.save(Guatemala);
    	countryRepository.save(Guernesey);
    	countryRepository.save(Guinée);
    	countryRepository.save(GuinéeBissau);
    	countryRepository.save(Guinéeéquatoriale);
    	countryRepository.save(Guyana);
    	countryRepository.save(Guyane);
    	countryRepository.save(Haïti);
    	countryRepository.save(ÎlesHeardetMacDonald);
    	countryRepository.save(Honduras);
    	countryRepository.save(HongKong);
    	countryRepository.save(Hongrie);
    	countryRepository.save(ÎledeMan);
    	countryRepository.save(ÎlesmineureséloignéesdesÉtatsUnis);
    	countryRepository.save(ÎlesViergesbritanniques);
    	countryRepository.save(ÎlesViergesdesÉtatsUnis);
    	countryRepository.save(Inde);
    	countryRepository.save(Indonésie);
    	countryRepository.save(Iran);
    	countryRepository.save(Irak);
    	countryRepository.save(Irlande);
    	countryRepository.save(Islande);
    	countryRepository.save(Israël);
    	countryRepository.save(Italie);
    	countryRepository.save(Jamaïque);
    	countryRepository.save(Japon);
    	countryRepository.save(Jersey);
    	countryRepository.save(Jordanie);
    	countryRepository.save(Kazakhstan);
    	countryRepository.save(Kenya);
    	countryRepository.save(Kirghizistan);
    	countryRepository.save(Kiribati);
    	countryRepository.save(Koweït);
    	countryRepository.save(Laos);
    	countryRepository.save(Lesotho);
    	countryRepository.save(Lettonie);
    	countryRepository.save(Liban);
    	countryRepository.save(Liberia);
    	countryRepository.save(Libye);
    	countryRepository.save(Liechtenstein);
    	countryRepository.save(Lituanie);
    	countryRepository.save(Luxembourg);
    	countryRepository.save(Macao);
    	countryRepository.save(MacédoineduNord);
    	countryRepository.save(Madagascar);
    	countryRepository.save(Malaisie);
    	countryRepository.save(Malawi);
    	countryRepository.save(Maldives);
    	countryRepository.save(Mali);
    	countryRepository.save(Malte);
    	countryRepository.save(ÎlesMariannesduNord);
    	countryRepository.save(Maroc);
    	countryRepository.save(ÎlesMarshall);
    	countryRepository.save(Martinique);
    	countryRepository.save(Maurice);
    	countryRepository.save(Mauritanie);
    	countryRepository.save(Mayotte);
    	countryRepository.save(Mexique);
    	countryRepository.save(ÉtatsfédérésdeMicronésie);
    	countryRepository.save(Moldavie);
    	countryRepository.save(Monaco);
    	countryRepository.save(Mongolie);
    	countryRepository.save(Monténégro);
    	countryRepository.save(Montserrat);
    	countryRepository.save(Mozambique);
    	countryRepository.save(Birmanie);
    	countryRepository.save(Namibie);
    	countryRepository.save(Nauru);
    	countryRepository.save(Népal);
    	countryRepository.save(Nicaragua);
    	countryRepository.save(Niger);
    	countryRepository.save(Nigeria);
    	countryRepository.save(Niue);
    	countryRepository.save(ÎleNorfolk);
    	countryRepository.save(Norvège);
    	countryRepository.save(NouvelleCalédonie);
    	countryRepository.save(NouvelleZélande);
    	countryRepository.save(TerritoirebritanniquedelocéanIndien);
    	countryRepository.save(Oman);
    	countryRepository.save(Ouganda);
    	countryRepository.save(Ouzbékistan);
    	countryRepository.save(Pakistan);
    	countryRepository.save(Palaos);
    	countryRepository.save(Palestine);
    	countryRepository.save(Panama);
    	countryRepository.save(PapouasieNouvelleGuinée);
    	countryRepository.save(Paraguay);
    	countryRepository.save(PaysBas);
    	countryRepository.save(Pérou);
    	countryRepository.save(Philippines);
    	countryRepository.save(ÎlesPitcairn);
    	countryRepository.save(Pologne);
    	countryRepository.save(Polynésiefrançaise);
    	countryRepository.save(PortoRico);
    	countryRepository.save(Portugal);
    	countryRepository.save(Qatar);
    	countryRepository.save(LaRéunion);
    	countryRepository.save(Roumanie);
    	countryRepository.save(RoyaumeUni);
    	countryRepository.save(Russie);
    	countryRepository.save(Rwanda);
    	countryRepository.save(Républiquearabesahraouiedémocratique);
    	countryRepository.save(SaintBarthélemy);
    	countryRepository.save(SaintChristopheetNiévès);
    	countryRepository.save(SaintMarin);
    	countryRepository.save(SaintMartinFr);
    	countryRepository.save(SaintMartinNl);
    	countryRepository.save(SaintPierreetMiquelon);
    	countryRepository.save(SaintSiège);
    	countryRepository.save(SaintVincentetlesGrenadines);
    	countryRepository.save(SainteHélène);
    	countryRepository.save(SainteLucie);
    	countryRepository.save(Salomon);
    	countryRepository.save(Samoa);
    	countryRepository.save(Samoaaméricaines);
    	countryRepository.save(SaoToméetPrincipe);
    	countryRepository.save(Sénégal);
    	countryRepository.save(Serbie);
    	countryRepository.save(Seychelles);
    	countryRepository.save(SierraLeone);
    	countryRepository.save(Singapour);
    	countryRepository.save(Slovaquie);
    	countryRepository.save(Slovénie);
    	countryRepository.save(Somalie);
    	countryRepository.save(Soudan);
    	countryRepository.save(SoudanduSud);
    	countryRepository.save(SriLanka);
    	countryRepository.save(Suède);
    	countryRepository.save(Suisse);
    	countryRepository.save(Suriname);
    	countryRepository.save(SvalbardetileJanMayen);
    	countryRepository.save(Swaziland);
    	countryRepository.save(Syrie);
    	countryRepository.save(Tadjikistan);
    	countryRepository.save(Taïwan);
    	countryRepository.save(Tanzanie);
    	countryRepository.save(Tchad);
    	countryRepository.save(Tchéquie);
    	countryRepository.save(Terresaustralesetantarctiquesfrançaises);
    	countryRepository.save(Thaïlande);
    	countryRepository.save(Timororiental);
    	countryRepository.save(Togo);
    	countryRepository.save(Tokelau);
    	countryRepository.save(Tonga);
    	countryRepository.save(TrinitéetTobago);
    	countryRepository.save(Tunisie);
    	countryRepository.save(Turkménistan);
    	countryRepository.save(ÎlesTurquesetCaïques);
    	countryRepository.save(Turquie);
    	countryRepository.save(Tuvalu);
    	countryRepository.save(Ukraine);
    	countryRepository.save(Uruguay);
    	countryRepository.save(Vanuatu);
    	countryRepository.save(Venezuela);
    	countryRepository.save(ViêtNam);
    	countryRepository.save(WallisetFutuna);
    	countryRepository.save(Yémen);
    	countryRepository.save(Zambie);
    	countryRepository.save(Zimbabwe);

      log.info("Preloading " + repository.save(new Area("AF", "Afrique", null)));
      log.info("Preloading " + repository.save(new Area("AFN", "Afrique du nord / Moyen-Orient", null)));
      log.info("Preloading " + repository.save(new Area("AM", "Amérique", null)));
      log.info("Preloading " + repository.save(new Area("ANT", "Antarctique", null)));
      log.info("Preloading " + repository.save(new Area("AS", "Asie-Océanie", null)));
      log.info("Preloading " + repository.save(new Area("EU", "Europe", this.countryList)));

    };
  }
}