package fr.pontos3.rise.riserest;

import lombok.extern.slf4j.Slf4j;

import java.util.ArrayList;
import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@Slf4j
class LoadDatabase {

    private List<Country> countryList = new ArrayList<Country>();
/*	
	private Country france = new Country().builder().iso2("fr").iso3("fra").isoNumeric(262).
			usualName("France").officialName("France").shortName("France").
			longitude(2.21).latitude(46.22).build();
	
	private Country spain = new Country().builder().iso2("es").iso3("esp").isoNumeric(724).
			usualName("Espagne").officialName("Espagne").shortName("Espagne").
			longitude(-3.74).latitude(40.46).build();
			
*/
    private Country Afghanistan_AF= new Country().builder().iso3("AFG").iso2("AF").isoNumeric(4).usualName("Afghanistan").officialName("AFGHANISTAN").shortName("Afghanistan").build();
    private Country Afrique_du_Sud_ZA= new Country().builder().iso3("ZAF").iso2("ZA").isoNumeric(710).usualName("Afrique du Sud").officialName("AFRIQUE DU SUD").shortName("Afrique du Sud").build();
    private Country Îles_Åland_AX= new Country().builder().iso3("ALA").iso2("AX").isoNumeric(248).usualName("Îles Åland").officialName("ÅLAND, ÎLES").shortName("Îles Åland").build();
    private Country Albanie_AL= new Country().builder().iso3("ALB").iso2("AL").isoNumeric(8).usualName("Albanie").officialName("ALBANIE").shortName("Albanie").build();
    private Country Algérie_DZ= new Country().builder().iso3("DZA").iso2("DZ").isoNumeric(12).usualName("Algérie").officialName("ALGÉRIE").shortName("Algérie").build();
    private Country Allemagne_DE= new Country().builder().iso3("DEU").iso2("DE").isoNumeric(276).usualName("Allemagne").officialName("ALLEMAGNE").shortName("Allemagne").build();
    private Country Andorre_AD= new Country().builder().iso3("AND").iso2("AD").isoNumeric(20).usualName("Andorre").officialName("ANDORRE").shortName("Andorre").build();
    private Country Angola_AO= new Country().builder().iso3("AGO").iso2("AO").isoNumeric(24).usualName("Angola").officialName("ANGOLA").shortName("Angola").build();
    private Country Anguilla_AI= new Country().builder().iso3("AIA").iso2("AI").isoNumeric(660).usualName("Anguilla").officialName("ANGUILLA").shortName("Anguilla").build();
    private Country Antarctique_AQ= new Country().builder().iso3("ATA").iso2("AQ").isoNumeric(10).usualName("Antarctique").officialName("ANTARCTIQUE").shortName("Antarctique").build();
    private Country Antigua_et_Barbuda_AG= new Country().builder().iso3("ATG").iso2("AG").isoNumeric(28).usualName("Antigua-et-Barbuda").officialName("ANTIGUA-ET-BARBUDA").shortName("Antigua-et-Barbuda").build();
    private Country Arabie_saoudite_SA= new Country().builder().iso3("SAU").iso2("SA").isoNumeric(682).usualName("Arabie saoudite").officialName("ARABIE SAOUDITE").shortName("Arabie saoudite").build();
    private Country Argentine_AR= new Country().builder().iso3("ARG").iso2("AR").isoNumeric(32).usualName("Argentine").officialName("ARGENTINE").shortName("Argentine").build();
    private Country Arménie_AM= new Country().builder().iso3("ARM").iso2("AM").isoNumeric(51).usualName("Arménie").officialName("ARMÉNIE").shortName("Arménie").build();
    private Country Aruba_AW= new Country().builder().iso3("ABW").iso2("AW").isoNumeric(533).usualName("Aruba").officialName("ARUBA").shortName("Aruba").build();
    private Country Australie_AU= new Country().builder().iso3("AUS").iso2("AU").isoNumeric(36).usualName("Australie").officialName("AUSTRALIE").shortName("Australie").build();
    private Country Autriche_AT= new Country().builder().iso3("AUT").iso2("AT").isoNumeric(40).usualName("Autriche").officialName("AUTRICHE").shortName("Autriche").build();
    private Country Azerbaïdjan_AZ= new Country().builder().iso3("AZE").iso2("AZ").isoNumeric(31).usualName("Azerbaïdjan").officialName("AZERBAÏDJAN").shortName("Azerbaïdjan").build();
    private Country Bahamas_BS= new Country().builder().iso3("BHS").iso2("BS").isoNumeric(44).usualName("Bahamas").officialName("BAHAMAS").shortName("Bahamas").build();
    private Country Bahreïn_BH= new Country().builder().iso3("BHR").iso2("BH").isoNumeric(48).usualName("Bahreïn").officialName("BAHREÏN").shortName("Bahreïn").build();
    private Country Bangladesh_BD= new Country().builder().iso3("BGD").iso2("BD").isoNumeric(50).usualName("Bangladesh").officialName("BANGLADESH").shortName("Bangladesh").build();
    private Country Barbade_BB= new Country().builder().iso3("BRB").iso2("BB").isoNumeric(52).usualName("Barbade").officialName("BARBADE").shortName("Barbade").build();
    private Country Biélorussie_BY= new Country().builder().iso3("BLR").iso2("BY").isoNumeric(112).usualName("Biélorussie").officialName("BÉLARUS").shortName("Biélorussie").build();
    private Country Belgique_BE= new Country().builder().iso3("BEL").iso2("BE").isoNumeric(56).usualName("Belgique").officialName("BELGIQUE").shortName("Belgique").build();
    private Country Belize_BZ= new Country().builder().iso3("BLZ").iso2("BZ").isoNumeric(84).usualName("Belize").officialName("BELIZE").shortName("Belize").build();
    private Country Bénin_BJ= new Country().builder().iso3("BEN").iso2("BJ").isoNumeric(204).usualName("Bénin").officialName("BÉNIN").shortName("Bénin").build();
    private Country Bermudes_BM= new Country().builder().iso3("BMU").iso2("BM").isoNumeric(60).usualName("Bermudes").officialName("BERMUDES").shortName("Bermudes").build();
    private Country Bhoutan_BT= new Country().builder().iso3("BTN").iso2("BT").isoNumeric(64).usualName("Bhoutan").officialName("BHOUTAN").shortName("Bhoutan").build();
    private Country Bolivie_BO= new Country().builder().iso3("BOL").iso2("BO").isoNumeric(68).usualName("Bolivie").officialName("BOLIVIE, ÉTAT PLURINATIONAL DE").shortName("Bolivie").build();
    private Country Pays_Bas_caribéens_BQ= new Country().builder().iso3("BES").iso2("BQ").isoNumeric(535).usualName("Pays-Bas caribéens").officialName("BONAIRE, SAINT-EUSTACHE ET SABA").shortName("Pays-Bas caribéens").build();
    private Country Bosnie_Herzégovine_BA= new Country().builder().iso3("BIH").iso2("BA").isoNumeric(70).usualName("Bosnie-Herzégovine").officialName("BOSNIE-HERZÉGOVINE").shortName("Bosnie-Herzégovine").build();
    private Country Botswana_BW= new Country().builder().iso3("BWA").iso2("BW").isoNumeric(72).usualName("Botswana").officialName("BOTSWANA").shortName("Botswana").build();
    private Country Île_Bouvet_BV= new Country().builder().iso3("BVT").iso2("BV").isoNumeric(74).usualName(" Île Bouvet").officialName("BOUVET, ÎLE").shortName(" Île Bouvet").build();
    private Country Brésil_BR= new Country().builder().iso3("BRA").iso2("BR").isoNumeric(76).usualName("Brésil").officialName("BRÉSIL").shortName("Brésil").build();
    private Country Brunei_BN= new Country().builder().iso3("BRN").iso2("BN").isoNumeric(96).usualName("Brunei").officialName("BRUNÉI DARUSSALAM").shortName("Brunei").build();
    private Country Bulgarie_BG= new Country().builder().iso3("BGR").iso2("BG").isoNumeric(100).usualName("Bulgarie").officialName("BULGARIE").shortName("Bulgarie").build();
    private Country Burkina_Faso_BF= new Country().builder().iso3("BFA").iso2("BF").isoNumeric(854).usualName("Burkina Faso").officialName("BURKINA FASO").shortName("Burkina Faso").build();
    private Country Burundi_BI= new Country().builder().iso3("BDI").iso2("BI").isoNumeric(108).usualName("Burundi").officialName("BURUNDI").shortName("Burundi").build();
    private Country Îles_Caïmans_KY= new Country().builder().iso3("CYM").iso2("KY").isoNumeric(136).usualName("Îles Caïmans").officialName("CAÏMANES, ÎLES").shortName("Îles Caïmans").build();
    private Country Cambodge_KH= new Country().builder().iso3("KHM").iso2("KH").isoNumeric(116).usualName("Cambodge").officialName("CAMBODGE").shortName("Cambodge").build();
    private Country Cameroun_CM= new Country().builder().iso3("CMR").iso2("CM").isoNumeric(120).usualName("Cameroun").officialName("CAMEROUN").shortName("Cameroun").build();
    private Country Canada_CA= new Country().builder().iso3("CAN").iso2("CA").isoNumeric(124).usualName("Canada").officialName("CANADA").shortName("Canada").build();
    private Country Cap_Vert_CV= new Country().builder().iso3("CPV").iso2("CV").isoNumeric(132).usualName("Cap-Vert").officialName("CABO VERDE").shortName("Cap-Vert").build();
    private Country République_centrafricaine_CF= new Country().builder().iso3("CAF").iso2("CF").isoNumeric(140).usualName("République centrafricaine").officialName("CENTRAFRICAINE, RÉPUBLIQUE").shortName("République centrafricaine").build();
    private Country Chili_CL= new Country().builder().iso3("CHL").iso2("CL").isoNumeric(152).usualName("Chili").officialName("CHILI").shortName("Chili").build();
    private Country Chine_CN= new Country().builder().iso3("CHN").iso2("CN").isoNumeric(156).usualName("Chine").officialName("CHINE").shortName("Chine").build();
    private Country Île_Christmas_CX= new Country().builder().iso3("CXR").iso2("CX").isoNumeric(162).usualName("Île Christmas").officialName("CHRISTMAS, ÎLE").shortName("Île Christmas").build();
    private Country Chypre__pays__CY= new Country().builder().iso3("CYP").iso2("CY").isoNumeric(196).usualName("Chypre (pays)").officialName("CHYPRE").shortName("Chypre (pays)").build();
    private Country Îles_Cocos_CC= new Country().builder().iso3("CCK").iso2("CC").isoNumeric(166).usualName("Îles Cocos").officialName("COCOS (KEELING), ÎLES").shortName("Îles Cocos").build();
    private Country Colombie_CO= new Country().builder().iso3("COL").iso2("CO").isoNumeric(170).usualName("Colombie").officialName("COLOMBIE").shortName("Colombie").build();
    private Country Comores__pays__KM= new Country().builder().iso3("COM").iso2("KM").isoNumeric(174).usualName("Comores (pays)").officialName("COMORES").shortName("Comores (pays)").build();
    private Country République_du_Congo_CG= new Country().builder().iso3("COG").iso2("CG").isoNumeric(178).usualName("République du Congo").officialName("CONGO").shortName("République du Congo").build();
    private Country République_démocratique_du_Congo_CD= new Country().builder().iso3("COD").iso2("CD").isoNumeric(180).usualName("République démocratique du Congo").officialName("CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU").shortName("République démocratique du Congo").build();
    private Country Îles_Cook_CK= new Country().builder().iso3("COK").iso2("CK").isoNumeric(184).usualName("Îles Cook").officialName("COOK, ÎLES").shortName("Îles Cook").build();
    private Country Corée_du_Sud_KR= new Country().builder().iso3("KOR").iso2("KR").isoNumeric(410).usualName("Corée du Sud").officialName("CORÉE, RÉPUBLIQUE DE").shortName("Corée du Sud").build();
    private Country Corée_du_Nord_KP= new Country().builder().iso3("PRK").iso2("KP").isoNumeric(408).usualName("Corée du Nord").officialName("CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE").shortName("Corée du Nord").build();
    private Country Costa_Rica_CR= new Country().builder().iso3("CRI").iso2("CR").isoNumeric(188).usualName("Costa Rica").officialName("COSTA RICA").shortName("Costa Rica").build();
    private Country Côte_d_Ivoire_CI= new Country().builder().iso3("CIV").iso2("CI").isoNumeric(384).usualName("Côte d'Ivoire").officialName("CÔTE D’IVOIRE").shortName("Côte d'Ivoire").build();
    private Country Croatie_HR= new Country().builder().iso3("HRV").iso2("HR").isoNumeric(191).usualName("Croatie").officialName("CROATIE").shortName("Croatie").build();
    private Country Cuba_CU= new Country().builder().iso3("CUB").iso2("CU").isoNumeric(192).usualName("Cuba").officialName("CUBA").shortName("Cuba").build();
    private Country Curaçao_CW= new Country().builder().iso3("CUW").iso2("CW").isoNumeric(531).usualName("Curaçao").officialName("CURAÇAO").shortName("Curaçao").build();
    private Country Danemark_DK= new Country().builder().iso3("DNK").iso2("DK").isoNumeric(208).usualName("Danemark").officialName("DANEMARK").shortName("Danemark").build();
    private Country Djibouti_DJ= new Country().builder().iso3("DJI").iso2("DJ").isoNumeric(262).usualName("Djibouti").officialName("DJIBOUTI").shortName("Djibouti").build();
    private Country République_dominicaine_DO= new Country().builder().iso3("DOM").iso2("DO").isoNumeric(214).usualName("République dominicaine").officialName("DOMINICAINE, RÉPUBLIQUE").shortName("République dominicaine").build();
    private Country Dominique_DM= new Country().builder().iso3("DMA").iso2("DM").isoNumeric(212).usualName("Dominique").officialName("DOMINIQUE").shortName("Dominique").build();
    private Country Égypte_EG= new Country().builder().iso3("EGY").iso2("EG").isoNumeric(818).usualName("Égypte").officialName("ÉGYPTE").shortName("Égypte").build();
    private Country Salvador_SV= new Country().builder().iso3("SLV").iso2("SV").isoNumeric(222).usualName("Salvador").officialName("EL SALVADOR").shortName("Salvador").build();
    private Country Émirats_arabes_unis_AE= new Country().builder().iso3("ARE").iso2("AE").isoNumeric(784).usualName("Émirats arabes unis").officialName("ÉMIRATS ARABES UNIS").shortName("Émirats arabes unis").build();
    private Country Équateur__pays__EC= new Country().builder().iso3("ECU").iso2("EC").isoNumeric(218).usualName("Équateur (pays)").officialName("ÉQUATEUR").shortName("Équateur (pays)").build();
    private Country Érythrée_ER= new Country().builder().iso3("ERI").iso2("ER").isoNumeric(232).usualName("Érythrée").officialName("ÉRYTHRÉE").shortName("Érythrée").build();
    private Country Espagne_ES= new Country().builder().iso3("ESP").iso2("ES").isoNumeric(724).usualName("Espagne").officialName("ESPAGNE").shortName("Espagne").build();
    private Country Estonie_EE= new Country().builder().iso3("EST").iso2("EE").isoNumeric(233).usualName("Estonie").officialName("ESTONIE").shortName("Estonie").build();
    private Country États_Unis_US= new Country().builder().iso3("USA").iso2("US").isoNumeric(840).usualName("États-Unis").officialName("ÉTATS-UNIS").shortName("États-Unis").build();
    private Country Éthiopie_ET= new Country().builder().iso3("ETH").iso2("ET").isoNumeric(231).usualName("Éthiopie").officialName("ÉTHIOPIE").shortName("Éthiopie").build();
    private Country Malouines_FK= new Country().builder().iso3("FLK").iso2("FK").isoNumeric(238).usualName("Malouines").officialName("FALKLAND, ÎLES (MALVINAS)").shortName("Malouines").build();
    private Country Îles_Féroé_FO= new Country().builder().iso3("FRO").iso2("FO").isoNumeric(234).usualName("Îles Féroé").officialName("FÉROÉ, ÎLES").shortName("Îles Féroé").build();
    private Country Fidji_FJ= new Country().builder().iso3("FJI").iso2("FJ").isoNumeric(242).usualName("Fidji").officialName("FIDJI").shortName("Fidji").build();
    private Country Finlande_FI= new Country().builder().iso3("FIN").iso2("FI").isoNumeric(246).usualName("Finlande").officialName("FINLANDE").shortName("Finlande").build();
    private Country France_FR= new Country().builder().iso3("FRA").iso2("FR").isoNumeric(250).usualName("France").officialName("FRANCE").shortName("France").build();
    private Country Gabon_GA= new Country().builder().iso3("GAB").iso2("GA").isoNumeric(266).usualName("Gabon").officialName("GABON").shortName("Gabon").build();
    private Country Gambie_GM= new Country().builder().iso3("GMB").iso2("GM").isoNumeric(270).usualName("Gambie").officialName("GAMBIE").shortName("Gambie").build();
    private Country Géorgie__pays__GE= new Country().builder().iso3("GEO").iso2("GE").isoNumeric(268).usualName("Géorgie (pays)").officialName("GÉORGIE").shortName("Géorgie (pays)").build();
    private Country Géorgie_du_Sud_et_les_îles_Sandwich_du_Sud_GS= new Country().builder().iso3("SGS").iso2("GS").isoNumeric(239).usualName("Géorgie du Sud-et-les îles Sandwich du Sud").officialName("GÉORGIE DU SUD ET LES ÎLES SANDWICH DU SUD").shortName("Géorgie du Sud-et-les îles Sandwich du Sud").build();
    private Country Ghana_GH= new Country().builder().iso3("GHA").iso2("GH").isoNumeric(288).usualName("Ghana").officialName("GHANA").shortName("Ghana").build();
    private Country Gibraltar_GI= new Country().builder().iso3("GIB").iso2("GI").isoNumeric(292).usualName("Gibraltar").officialName("GIBRALTAR").shortName("Gibraltar").build();
    private Country Grèce_GR= new Country().builder().iso3("GRC").iso2("GR").isoNumeric(300).usualName("Grèce").officialName("GRÈCE").shortName("Grèce").build();
    private Country Grenade__pays__GD= new Country().builder().iso3("GRD").iso2("GD").isoNumeric(308).usualName("Grenade (pays)").officialName("GRENADE").shortName("Grenade (pays)").build();
    private Country Groenland_GL= new Country().builder().iso3("GRL").iso2("GL").isoNumeric(304).usualName("Groenland").officialName("GROENLAND").shortName("Groenland").build();
    private Country Guadeloupe_GP= new Country().builder().iso3("GLP").iso2("GP").isoNumeric(312).usualName("Guadeloupe").officialName("GUADELOUPE").shortName("Guadeloupe").build();
    private Country Guam_GU= new Country().builder().iso3("GUM").iso2("GU").isoNumeric(316).usualName("Guam").officialName("GUAM").shortName("Guam").build();
    private Country Guatemala_GT= new Country().builder().iso3("GTM").iso2("GT").isoNumeric(320).usualName("Guatemala").officialName("GUATEMALA").shortName("Guatemala").build();
    private Country Guernesey_GG= new Country().builder().iso3("GGY").iso2("GG").isoNumeric(831).usualName("Guernesey").officialName("GUERNESEY").shortName("Guernesey").build();
    private Country Guinée_GN= new Country().builder().iso3("GIN").iso2("GN").isoNumeric(324).usualName("Guinée").officialName("GUINÉE").shortName("Guinée").build();
    private Country Guinée_Bissau_GW= new Country().builder().iso3("GNB").iso2("GW").isoNumeric(624).usualName("Guinée-Bissau").officialName("GUINÉE-BISSAU").shortName("Guinée-Bissau").build();
    private Country Guinée_équatoriale_GQ= new Country().builder().iso3("GNQ").iso2("GQ").isoNumeric(226).usualName("Guinée équatoriale").officialName("GUINÉE ÉQUATORIALE").shortName("Guinée équatoriale").build();
    private Country Guyana_GY= new Country().builder().iso3("GUY").iso2("GY").isoNumeric(328).usualName("Guyana").officialName("GUYANA").shortName("Guyana").build();
    private Country Guyane_GF= new Country().builder().iso3("GUF").iso2("GF").isoNumeric(254).usualName("Guyane").officialName("GUYANE FRANÇAISE").shortName("Guyane").build();
    private Country Haïti_HT= new Country().builder().iso3("HTI").iso2("HT").isoNumeric(332).usualName("Haïti").officialName("HAÏTI").shortName("Haïti").build();
    private Country Îles_Heard_et_MacDonald_HM= new Country().builder().iso3("HMD").iso2("HM").isoNumeric(334).usualName("Îles Heard-et-MacDonald").officialName("HEARD ET MACDONALD, ÎLES").shortName("Îles Heard-et-MacDonald").build();
    private Country Honduras_HN= new Country().builder().iso3("HND").iso2("HN").isoNumeric(340).usualName("Honduras").officialName("HONDURAS").shortName("Honduras").build();
    private Country Hong_Kong_HK= new Country().builder().iso3("HKG").iso2("HK").isoNumeric(344).usualName("Hong Kong").officialName("HONG KONG").shortName("Hong Kong").build();
    private Country Hongrie_HU= new Country().builder().iso3("HUN").iso2("HU").isoNumeric(348).usualName("Hongrie").officialName("HONGRIE").shortName("Hongrie").build();
    private Country Île_de_Man_IM= new Country().builder().iso3("IMN").iso2("IM").isoNumeric(833).usualName("Île de Man").officialName("ÎLE DE MAN").shortName("Île de Man").build();
    private Country Îles_mineures_éloignées_des_États_Unis_UM= new Country().builder().iso3("UMI").iso2("UM").isoNumeric(581).usualName(" Îles mineures éloignées des États-Unis").officialName("ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS").shortName(" Îles mineures éloignées des États-Unis").build();
    private Country Îles_Vierges_britanniques_VG= new Country().builder().iso3("VGB").iso2("VG").isoNumeric(92).usualName("Îles Vierges britanniques").officialName("ÎLES VIERGES BRITANNIQUES").shortName("Îles Vierges britanniques").build();
    private Country Îles_Vierges_des_États_Unis_VI= new Country().builder().iso3("VIR").iso2("VI").isoNumeric(850).usualName("Îles Vierges des États-Unis").officialName("ÎLES VIERGES DES ÉTATS-UNIS").shortName("Îles Vierges des États-Unis").build();
    private Country Inde_IN= new Country().builder().iso3("IND").iso2("IN").isoNumeric(356).usualName("Inde").officialName("INDE").shortName("Inde").build();
    private Country Indonésie_ID= new Country().builder().iso3("IDN").iso2("ID").isoNumeric(360).usualName("Indonésie").officialName("INDONÉSIE").shortName("Indonésie").build();
    private Country Iran_IR= new Country().builder().iso3("IRN").iso2("IR").isoNumeric(364).usualName("Iran").officialName("IRAN, RÉPUBLIQUE ISLAMIQUE D'").shortName("Iran").build();
    private Country Irak_IQ= new Country().builder().iso3("IRQ").iso2("IQ").isoNumeric(368).usualName("Irak").officialName("IRAQ").shortName("Irak").build();
    private Country Irlande__pays__IE= new Country().builder().iso3("IRL").iso2("IE").isoNumeric(372).usualName("Irlande (pays)").officialName("IRLANDE").shortName("Irlande (pays)").build();
    private Country Islande_IS= new Country().builder().iso3("ISL").iso2("IS").isoNumeric(352).usualName("Islande").officialName("ISLANDE").shortName("Islande").build();
    private Country Israël_IL= new Country().builder().iso3("ISR").iso2("IL").isoNumeric(376).usualName("Israël").officialName("ISRAËL").shortName("Israël").build();
    private Country Italie_IT= new Country().builder().iso3("ITA").iso2("IT").isoNumeric(380).usualName("Italie").officialName("ITALIE").shortName("Italie").build();
    private Country Jamaïque_JM= new Country().builder().iso3("JAM").iso2("JM").isoNumeric(388).usualName("Jamaïque").officialName("JAMAÏQUE").shortName("Jamaïque").build();
    private Country Japon_JP= new Country().builder().iso3("JPN").iso2("JP").isoNumeric(392).usualName("Japon").officialName("JAPON").shortName("Japon").build();
    private Country Jersey_JE= new Country().builder().iso3("JEY").iso2("JE").isoNumeric(832).usualName("Jersey").officialName("JERSEY").shortName("Jersey").build();
    private Country Jordanie_JO= new Country().builder().iso3("JOR").iso2("JO").isoNumeric(400).usualName("Jordanie").officialName("JORDANIE").shortName("Jordanie").build();
    private Country Kazakhstan_KZ= new Country().builder().iso3("KAZ").iso2("KZ").isoNumeric(398).usualName("Kazakhstan").officialName("KAZAKHSTAN").shortName("Kazakhstan").build();
    private Country Kenya_KE= new Country().builder().iso3("KEN").iso2("KE").isoNumeric(404).usualName("Kenya").officialName("KENYA").shortName("Kenya").build();
    private Country Kirghizistan_KG= new Country().builder().iso3("KGZ").iso2("KG").isoNumeric(417).usualName("Kirghizistan").officialName("KIRGHIZISTAN").shortName("Kirghizistan").build();
    private Country Kiribati_KI= new Country().builder().iso3("KIR").iso2("KI").isoNumeric(296).usualName("Kiribati").officialName("KIRIBATI").shortName("Kiribati").build();
    private Country Koweït_KW= new Country().builder().iso3("KWT").iso2("KW").isoNumeric(414).usualName("Koweït").officialName("KOWEÏT").shortName("Koweït").build();
    private Country Laos_LA= new Country().builder().iso3("LAO").iso2("LA").isoNumeric(418).usualName("Laos").officialName("LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE").shortName("Laos").build();
    private Country Lesotho_LS= new Country().builder().iso3("LSO").iso2("LS").isoNumeric(426).usualName("Lesotho").officialName("LESOTHO").shortName("Lesotho").build();
    private Country Lettonie_LV= new Country().builder().iso3("LVA").iso2("LV").isoNumeric(428).usualName("Lettonie").officialName("LETTONIE").shortName("Lettonie").build();
    private Country Liban_LB= new Country().builder().iso3("LBN").iso2("LB").isoNumeric(422).usualName("Liban").officialName("LIBAN").shortName("Liban").build();
    private Country Liberia_LR= new Country().builder().iso3("LBR").iso2("LR").isoNumeric(430).usualName("Liberia").officialName("LIBÉRIA").shortName("Liberia").build();
    private Country Libye_LY= new Country().builder().iso3("LBY").iso2("LY").isoNumeric(434).usualName("Libye").officialName("LIBYE").shortName("Libye").build();
    private Country Liechtenstein_LI= new Country().builder().iso3("LIE").iso2("LI").isoNumeric(438).usualName("Liechtenstein").officialName("LIECHTENSTEIN").shortName("Liechtenstein").build();
    private Country Lituanie_LT= new Country().builder().iso3("LTU").iso2("LT").isoNumeric(440).usualName("Lituanie").officialName("LITUANIE").shortName("Lituanie").build();
    private Country Luxembourg__pays__LU= new Country().builder().iso3("LUX").iso2("LU").isoNumeric(442).usualName("Luxembourg (pays)").officialName("LUXEMBOURG").shortName("Luxembourg (pays)").build();
    private Country Macao_MO= new Country().builder().iso3("MAC").iso2("MO").isoNumeric(446).usualName("Macao").officialName("MACAO").shortName("Macao").build();
    private Country Macédoine_du_Nord_MK= new Country().builder().iso3("MKD").iso2("MK").isoNumeric(807).usualName("Macédoine du Nord").officialName("RÉPUBLIQUE DE MACÉDOINE").shortName("Macédoine du Nord").build();
    private Country Madagascar_MG= new Country().builder().iso3("MDG").iso2("MG").isoNumeric(450).usualName("Madagascar").officialName("MADAGASCAR").shortName("Madagascar").build();
    private Country Malaisie_MY= new Country().builder().iso3("MYS").iso2("MY").isoNumeric(458).usualName("Malaisie").officialName("MALAISIE").shortName("Malaisie").build();
    private Country Malawi_MW= new Country().builder().iso3("MWI").iso2("MW").isoNumeric(454).usualName("Malawi").officialName("MALAWI").shortName("Malawi").build();
    private Country Maldives_MV= new Country().builder().iso3("MDV").iso2("MV").isoNumeric(462).usualName("Maldives").officialName("MALDIVES").shortName("Maldives").build();
    private Country Mali_ML= new Country().builder().iso3("MLI").iso2("ML").isoNumeric(466).usualName("Mali").officialName("MALI").shortName("Mali").build();
    private Country Malte_MT= new Country().builder().iso3("MLT").iso2("MT").isoNumeric(470).usualName("Malte").officialName("MALTE").shortName("Malte").build();
    private Country Îles_Mariannes_du_Nord_MP= new Country().builder().iso3("MNP").iso2("MP").isoNumeric(580).usualName("Îles Mariannes du Nord").officialName("MARIANNES DU NORD, ÎLES").shortName("Îles Mariannes du Nord").build();
    private Country Maroc_MA= new Country().builder().iso3("MAR").iso2("MA").isoNumeric(504).usualName("Maroc").officialName("MAROC").shortName("Maroc").build();
    private Country Îles_Marshall__pays__MH= new Country().builder().iso3("MHL").iso2("MH").isoNumeric(584).usualName("Îles Marshall (pays)").officialName("MARSHALL, ÎLES").shortName("Îles Marshall (pays)").build();
    private Country Martinique_MQ= new Country().builder().iso3("MTQ").iso2("MQ").isoNumeric(474).usualName("Martinique").officialName("MARTINIQUE").shortName("Martinique").build();
    private Country Maurice__pays__MU= new Country().builder().iso3("MUS").iso2("MU").isoNumeric(480).usualName("Maurice (pays)").officialName("MAURICE").shortName("Maurice (pays)").build();
    private Country Mauritanie_MR= new Country().builder().iso3("MRT").iso2("MR").isoNumeric(478).usualName("Mauritanie").officialName("MAURITANIE").shortName("Mauritanie").build();
    private Country Mayotte_YT= new Country().builder().iso3("MYT").iso2("YT").isoNumeric(175).usualName("Mayotte").officialName("MAYOTTE").shortName("Mayotte").build();
    private Country Mexique_MX= new Country().builder().iso3("MEX").iso2("MX").isoNumeric(484).usualName("Mexique").officialName("MEXIQUE").shortName("Mexique").build();
    private Country États_fédérés_de_Micronésie__pays__FM= new Country().builder().iso3("FSM").iso2("FM").isoNumeric(583).usualName("États fédérés de Micronésie (pays)").officialName("MICRONÉSIE, ÉTATS FÉDÉRÉS DE").shortName("États fédérés de Micronésie (pays)").build();
    private Country Moldavie_MD= new Country().builder().iso3("MDA").iso2("MD").isoNumeric(498).usualName("Moldavie").officialName("MOLDAVIE").shortName("Moldavie").build();
    private Country Monaco_MC= new Country().builder().iso3("MCO").iso2("MC").isoNumeric(492).usualName("Monaco").officialName("MONACO").shortName("Monaco").build();
    private Country Mongolie_MN= new Country().builder().iso3("MNG").iso2("MN").isoNumeric(496).usualName("Mongolie").officialName("MONGOLIE").shortName("Mongolie").build();
    private Country Monténégro_ME= new Country().builder().iso3("MNE").iso2("ME").isoNumeric(499).usualName("Monténégro").officialName("MONTÉNÉGRO").shortName("Monténégro").build();
    private Country Montserrat_MS= new Country().builder().iso3("MSR").iso2("MS").isoNumeric(500).usualName("Montserrat").officialName("MONTSERRAT").shortName("Montserrat").build();
    private Country Mozambique_MZ= new Country().builder().iso3("MOZ").iso2("MZ").isoNumeric(508).usualName("Mozambique").officialName("MOZAMBIQUE").shortName("Mozambique").build();
    private Country Birmanie_MM= new Country().builder().iso3("MMR").iso2("MM").isoNumeric(104).usualName("Birmanie").officialName("MYANMAR").shortName("Birmanie").build();
    private Country Namibie_NA= new Country().builder().iso3("NAM").iso2("NA").isoNumeric(516).usualName("Namibie").officialName("NAMIBIE").shortName("Namibie").build();
    private Country Nauru_NR= new Country().builder().iso3("NRU").iso2("NR").isoNumeric(520).usualName("Nauru").officialName("NAURU").shortName("Nauru").build();
    private Country Népal_NP= new Country().builder().iso3("NPL").iso2("NP").isoNumeric(524).usualName("Népal").officialName("NÉPAL").shortName("Népal").build();
    private Country Nicaragua_NI= new Country().builder().iso3("NIC").iso2("NI").isoNumeric(558).usualName("Nicaragua").officialName("NICARAGUA").shortName("Nicaragua").build();
    private Country Niger_NE= new Country().builder().iso3("NER").iso2("NE").isoNumeric(562).usualName("Niger").officialName("NIGER").shortName("Niger").build();
    private Country Nigeria_NG= new Country().builder().iso3("NGA").iso2("NG").isoNumeric(566).usualName("Nigeria").officialName("NIGÉRIA").shortName("Nigeria").build();
    private Country Niue_NU= new Country().builder().iso3("NIU").iso2("NU").isoNumeric(570).usualName("Niue").officialName("NIUÉ").shortName("Niue").build();
    private Country Île_Norfolk_NF= new Country().builder().iso3("NFK").iso2("NF").isoNumeric(574).usualName("Île Norfolk").officialName("NORFOLK, ÎLE").shortName("Île Norfolk").build();
    private Country Norvège_NO= new Country().builder().iso3("NOR").iso2("NO").isoNumeric(578).usualName("Norvège").officialName("NORVÈGE").shortName("Norvège").build();
    private Country Nouvelle_Calédonie_NC= new Country().builder().iso3("NCL").iso2("NC").isoNumeric(540).usualName("Nouvelle-Calédonie").officialName("NOUVELLE-CALÉDONIE").shortName("Nouvelle-Calédonie").build();
    private Country Nouvelle_Zélande_NZ= new Country().builder().iso3("NZL").iso2("NZ").isoNumeric(554).usualName("Nouvelle-Zélande").officialName("NOUVELLE-ZÉLANDE").shortName("Nouvelle-Zélande").build();
    private Country Territoire_britannique_de_l_océan_Indien_IO= new Country().builder().iso3("IOT").iso2("IO").isoNumeric(86).usualName("Territoire britannique de l'océan Indien").officialName("OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L'").shortName("Territoire britannique de l'océan Indien").build();
    private Country Oman_OM= new Country().builder().iso3("OMN").iso2("OM").isoNumeric(512).usualName("Oman").officialName("OMAN").shortName("Oman").build();
    private Country Ouganda_UG= new Country().builder().iso3("UGA").iso2("UG").isoNumeric(800).usualName("Ouganda").officialName("OUGANDA").shortName("Ouganda").build();
    private Country Ouzbékistan_UZ= new Country().builder().iso3("UZB").iso2("UZ").isoNumeric(860).usualName("Ouzbékistan").officialName("OUZBÉKISTAN").shortName("Ouzbékistan").build();
    private Country Pakistan_PK= new Country().builder().iso3("PAK").iso2("PK").isoNumeric(586).usualName("Pakistan").officialName("PAKISTAN").shortName("Pakistan").build();
    private Country Palaos_PW= new Country().builder().iso3("PLW").iso2("PW").isoNumeric(585).usualName("Palaos").officialName("PALAOS").shortName("Palaos").build();
    private Country Palestine_PS= new Country().builder().iso3("PSE").iso2("PS").isoNumeric(275).usualName("Palestine").officialName("ÉTAT DE PALESTINE").shortName("Palestine").build();
    private Country Panama_PA= new Country().builder().iso3("PAN").iso2("PA").isoNumeric(591).usualName("Panama").officialName("PANAMA").shortName("Panama").build();
    private Country Papouasie_Nouvelle_Guinée_PG= new Country().builder().iso3("PNG").iso2("PG").isoNumeric(598).usualName("Papouasie-Nouvelle-Guinée").officialName("PAPOUASIE-NOUVELLE-GUINÉE").shortName("Papouasie-Nouvelle-Guinée").build();
    private Country Paraguay_PY= new Country().builder().iso3("PRY").iso2("PY").isoNumeric(600).usualName("Paraguay").officialName("PARAGUAY").shortName("Paraguay").build();
    private Country Pays_Bas_NL= new Country().builder().iso3("NLD").iso2("NL").isoNumeric(528).usualName("Pays-Bas").officialName("PAYS-BAS").shortName("Pays-Bas").build();
    private Country Pérou_PE= new Country().builder().iso3("PER").iso2("PE").isoNumeric(604).usualName("Pérou").officialName("PÉROU").shortName("Pérou").build();
    private Country Philippines_PH= new Country().builder().iso3("PHL").iso2("PH").isoNumeric(608).usualName("Philippines").officialName("PHILIPPINES").shortName("Philippines").build();
    private Country Îles_Pitcairn_PN= new Country().builder().iso3("PCN").iso2("PN").isoNumeric(612).usualName("Îles Pitcairn").officialName("PITCAIRN").shortName("Îles Pitcairn").build();
    private Country Pologne_PL= new Country().builder().iso3("POL").iso2("PL").isoNumeric(616).usualName("Pologne").officialName("POLOGNE").shortName("Pologne").build();
    private Country Polynésie_française_PF= new Country().builder().iso3("PYF").iso2("PF").isoNumeric(258).usualName("Polynésie française").officialName("POLYNÉSIE FRANÇAISE").shortName("Polynésie française").build();
    private Country Porto_Rico_PR= new Country().builder().iso3("PRI").iso2("PR").isoNumeric(630).usualName("Porto Rico").officialName("PORTO RICO").shortName("Porto Rico").build();
    private Country Portugal_PT= new Country().builder().iso3("PRT").iso2("PT").isoNumeric(620).usualName("Portugal").officialName("PORTUGAL").shortName("Portugal").build();
    private Country Qatar_QA= new Country().builder().iso3("QAT").iso2("QA").isoNumeric(634).usualName("Qatar").officialName("QATAR").shortName("Qatar").build();
    private Country La_Réunion_RE= new Country().builder().iso3("REU").iso2("RE").isoNumeric(638).usualName("La Réunion").officialName("RÉUNION").shortName("La Réunion").build();
    private Country Roumanie_RO= new Country().builder().iso3("ROU").iso2("RO").isoNumeric(642).usualName("Roumanie").officialName("ROUMANIE").shortName("Roumanie").build();
    private Country Royaume_Uni_GB= new Country().builder().iso3("GBR").iso2("GB").isoNumeric(826).usualName("Royaume-Uni").officialName("ROYAUME-UNI").shortName("Royaume-Uni").build();
    private Country Russie_RU= new Country().builder().iso3("RUS").iso2("RU").isoNumeric(643).usualName("Russie").officialName("RUSSIE, FÉDÉRATION DE").shortName("Russie").build();
    private Country Rwanda_RW= new Country().builder().iso3("RWA").iso2("RW").isoNumeric(646).usualName("Rwanda").officialName("RWANDA").shortName("Rwanda").build();
    private Country République_arabe_sahraouie_démocratique_EH= new Country().builder().iso3("ESH").iso2("EH").isoNumeric(732).usualName("République arabe sahraouie démocratique").officialName("SAHARA OCCIDENTAL").shortName("République arabe sahraouie démocratique").build();
    private Country Saint_Barthélemy_BL= new Country().builder().iso3("BLM").iso2("BL").isoNumeric(652).usualName("Saint-Barthélemy").officialName("SAINT-BARTHÉLEMY").shortName("Saint-Barthélemy").build();
    private Country Saint_Christophe_et_Niévès_KN= new Country().builder().iso3("KNA").iso2("KN").isoNumeric(659).usualName("Saint-Christophe-et-Niévès").officialName("SAINT-KITTS-ET-NEVIS").shortName("Saint-Christophe-et-Niévès").build();
    private Country Saint_Marin_SM= new Country().builder().iso3("SMR").iso2("SM").isoNumeric(674).usualName("Saint-Marin").officialName("SAINT-MARIN").shortName("Saint-Marin").build();
    private Country Saint_Martin_MF= new Country().builder().iso3("MAF").iso2("MF").isoNumeric(663).usualName("Saint-Martin").officialName("SAINT-MARTIN (PARTIE FRANÇAISE)").shortName("Saint-Martin").build();
    private Country Saint_Martin_SX= new Country().builder().iso3("SXM").iso2("SX").isoNumeric(534).usualName("Saint-Martin").officialName("SAINT-MARTIN (PARTIE NÉERLANDAISE)").shortName("Saint-Martin").build();
    private Country Saint_Pierre_et_Miquelon_PM= new Country().builder().iso3("SPM").iso2("PM").isoNumeric(666).usualName("Saint-Pierre-et-Miquelon").officialName("SAINT-PIERRE-ET-MIQUELON").shortName("Saint-Pierre-et-Miquelon").build();
    private Country Saint_Siège__État_de_la_Cité_du_Vatican__VA= new Country().builder().iso3("VAT").iso2("VA").isoNumeric(336).usualName(" Saint-Siège (État de la Cité du Vatican)").officialName("SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)").shortName(" Saint-Siège (État de la Cité du Vatican)").build();
    private Country Saint_Vincent_et_les_Grenadines_VC= new Country().builder().iso3("VCT").iso2("VC").isoNumeric(670).usualName("Saint-Vincent-et-les-Grenadines").officialName("SAINT-VINCENT-ET-LES-GRENADINES").shortName("Saint-Vincent-et-les-Grenadines").build();
    private Country Sainte_Hélène_Ascension_et_Tristan_da_Cunha_SH= new Country().builder().iso3("SHN").iso2("SH").isoNumeric(654).usualName("Sainte-Hélène, Ascension et Tristan da Cunha").officialName("SAINTE-HÉLÈNE, ASCENSION ET TRISTAN DA CUNHA").shortName("Sainte-Hélène, Ascension et Tristan da Cunha").build();
    private Country Sainte_Lucie_LC= new Country().builder().iso3("LCA").iso2("LC").isoNumeric(662).usualName("Sainte-Lucie").officialName("SAINTE-LUCIE").shortName("Sainte-Lucie").build();
    private Country Salomon_SB= new Country().builder().iso3("SLB").iso2("SB").isoNumeric(90).usualName("Salomon").officialName("SALOMON, ÎLES").shortName("Salomon").build();
    private Country Samoa_WS= new Country().builder().iso3("WSM").iso2("WS").isoNumeric(882).usualName("Samoa").officialName("SAMOA").shortName("Samoa").build();
    private Country Samoa_américaines_AS= new Country().builder().iso3("ASM").iso2("AS").isoNumeric(16).usualName("Samoa américaines").officialName("SAMOA AMÉRICAINES").shortName("Samoa américaines").build();
    private Country Sao_Tomé_et_Principe_ST= new Country().builder().iso3("STP").iso2("ST").isoNumeric(678).usualName("Sao Tomé-et-Principe").officialName("SAO TOMÉ-ET-PRINCIPE").shortName("Sao Tomé-et-Principe").build();
    private Country Sénégal_SN= new Country().builder().iso3("SEN").iso2("SN").isoNumeric(686).usualName("Sénégal").officialName("SÉNÉGAL").shortName("Sénégal").build();
    private Country Serbie_RS= new Country().builder().iso3("SRB").iso2("RS").isoNumeric(688).usualName("Serbie").officialName("SERBIE").shortName("Serbie").build();
    private Country Seychelles_SC= new Country().builder().iso3("SYC").iso2("SC").isoNumeric(690).usualName("Seychelles").officialName("SEYCHELLES").shortName("Seychelles").build();
    private Country Sierra_Leone_SL= new Country().builder().iso3("SLE").iso2("SL").isoNumeric(694).usualName("Sierra Leone").officialName("SIERRA LEONE").shortName("Sierra Leone").build();
    private Country Singapour_SG= new Country().builder().iso3("SGP").iso2("SG").isoNumeric(702).usualName("Singapour").officialName("SINGAPOUR").shortName("Singapour").build();
    private Country Slovaquie_SK= new Country().builder().iso3("SVK").iso2("SK").isoNumeric(703).usualName("Slovaquie").officialName("SLOVAQUIE").shortName("Slovaquie").build();
    private Country Slovénie_SI= new Country().builder().iso3("SVN").iso2("SI").isoNumeric(705).usualName("Slovénie").officialName("SLOVÉNIE").shortName("Slovénie").build();
    private Country Somalie_SO= new Country().builder().iso3("SOM").iso2("SO").isoNumeric(706).usualName("Somalie").officialName("SOMALIE").shortName("Somalie").build();
    private Country Soudan_SD= new Country().builder().iso3("SDN").iso2("SD").isoNumeric(729).usualName("Soudan").officialName("SOUDAN").shortName("Soudan").build();
    private Country Soudan_du_Sud_SS= new Country().builder().iso3("SSD").iso2("SS").isoNumeric(728).usualName("Soudan du Sud").officialName("SOUDAN DU SUD").shortName("Soudan du Sud").build();
    private Country Sri_Lanka_LK= new Country().builder().iso3("LKA").iso2("LK").isoNumeric(144).usualName("Sri Lanka").officialName("SRI LANKA").shortName("Sri Lanka").build();
    private Country Suède_SE= new Country().builder().iso3("SWE").iso2("SE").isoNumeric(752).usualName("Suède").officialName("SUÈDE").shortName("Suède").build();
    private Country Suisse_CH= new Country().builder().iso3("CHE").iso2("CH").isoNumeric(756).usualName("Suisse").officialName("SUISSE").shortName("Suisse").build();
    private Country Suriname_SR= new Country().builder().iso3("SUR").iso2("SR").isoNumeric(740).usualName("Suriname").officialName("SURINAME").shortName("Suriname").build();
    private Country Svalbard_et_ile_Jan_Mayen_SJ= new Country().builder().iso3("SJM").iso2("SJ").isoNumeric(744).usualName("Svalbard et ile Jan Mayen").officialName("SVALBARD ET ÎLE JAN MAYEN").shortName("Svalbard et ile Jan Mayen").build();
    private Country Swaziland_SZ= new Country().builder().iso3("SWZ").iso2("SZ").isoNumeric(748).usualName("Swaziland").officialName("ESWATINI").shortName("Swaziland").build();
    private Country Syrie_SY= new Country().builder().iso3("SYR").iso2("SY").isoNumeric(760).usualName("Syrie").officialName("SYRIENNE, RÉPUBLIQUE ARABE").shortName("Syrie").build();
    private Country Tadjikistan_TJ= new Country().builder().iso3("TJK").iso2("TJ").isoNumeric(762).usualName("Tadjikistan").officialName("TADJIKISTAN").shortName("Tadjikistan").build();
    private Country Taïwan_République_de_Chine__Taïwan___TW= new Country().builder().iso3("TWN").iso2("TW").isoNumeric(158).usualName("Taïwan / (République de Chine (Taïwan))").officialName("TAÏWAN, PROVINCE DE CHINE").shortName("Taïwan / (République de Chine (Taïwan))").build();
    private Country Tanzanie_TZ= new Country().builder().iso3("TZA").iso2("TZ").isoNumeric(834).usualName("Tanzanie").officialName("TANZANIE, RÉPUBLIQUE UNIE DE").shortName("Tanzanie").build();
    private Country Tchad_TD= new Country().builder().iso3("TCD").iso2("TD").isoNumeric(148).usualName("Tchad").officialName("TCHAD").shortName("Tchad").build();
    private Country Tchéquie_CZ= new Country().builder().iso3("CZE").iso2("CZ").isoNumeric(203).usualName("Tchéquie").officialName("TCHÉQUIE").shortName("Tchéquie").build();
    private Country Terres_australes_et_antarctiques_françaises_TF= new Country().builder().iso3("ATF").iso2("TF").isoNumeric(260).usualName("Terres australes et antarctiques françaises").officialName("TERRES AUSTRALES FRANÇAISES").shortName("Terres australes et antarctiques françaises").build();
    private Country Thaïlande_TH= new Country().builder().iso3("THA").iso2("TH").isoNumeric(764).usualName("Thaïlande").officialName("THAÏLANDE").shortName("Thaïlande").build();
    private Country Timor_oriental_TL= new Country().builder().iso3("TLS").iso2("TL").isoNumeric(626).usualName("Timor oriental").officialName("TIMOR-LESTE").shortName("Timor oriental").build();
    private Country Togo_TG= new Country().builder().iso3("TGO").iso2("TG").isoNumeric(768).usualName("Togo").officialName("TOGO").shortName("Togo").build();
    private Country Tokelau_TK= new Country().builder().iso3("TKL").iso2("TK").isoNumeric(772).usualName("Tokelau").officialName("TOKELAU").shortName("Tokelau").build();
    private Country Tonga_TO= new Country().builder().iso3("TON").iso2("TO").isoNumeric(776).usualName("Tonga").officialName("TONGA").shortName("Tonga").build();
    private Country Trinité_et_Tobago_TT= new Country().builder().iso3("TTO").iso2("TT").isoNumeric(780).usualName("Trinité-et-Tobago").officialName("TRINITÉ-ET-TOBAGO").shortName("Trinité-et-Tobago").build();
    private Country Tunisie_TN= new Country().builder().iso3("TUN").iso2("TN").isoNumeric(788).usualName("Tunisie").officialName("TUNISIE").shortName("Tunisie").build();
    private Country Turkménistan_TM= new Country().builder().iso3("TKM").iso2("TM").isoNumeric(795).usualName("Turkménistan").officialName("TURKMÉNISTAN").shortName("Turkménistan").build();
    private Country Îles_Turques_et_Caïques_TC= new Country().builder().iso3("TCA").iso2("TC").isoNumeric(796).usualName("Îles Turques-et-Caïques").officialName("TURKS ET CAÏQUES, ÎLES").shortName("Îles Turques-et-Caïques").build();
    private Country Turquie_TR= new Country().builder().iso3("TUR").iso2("TR").isoNumeric(792).usualName("Turquie").officialName("TURQUIE").shortName("Turquie").build();
    private Country Tuvalu_TV= new Country().builder().iso3("TUV").iso2("TV").isoNumeric(798).usualName("Tuvalu").officialName("TUVALU").shortName("Tuvalu").build();
    private Country Ukraine_UA= new Country().builder().iso3("UKR").iso2("UA").isoNumeric(804).usualName("Ukraine").officialName("UKRAINE").shortName("Ukraine").build();
    private Country Uruguay_UY= new Country().builder().iso3("URY").iso2("UY").isoNumeric(858).usualName("Uruguay").officialName("URUGUAY").shortName("Uruguay").build();
    private Country Vanuatu_VU= new Country().builder().iso3("VUT").iso2("VU").isoNumeric(548).usualName("Vanuatu").officialName("VANUATU").shortName("Vanuatu").build();
    private Country Venezuela_VE= new Country().builder().iso3("VEN").iso2("VE").isoNumeric(862).usualName("Venezuela").officialName("VENEZUELA, RÉPUBLIQUE BOLIVARIENNE DU").shortName("Venezuela").build();
    private Country Viêt_Nam_VN= new Country().builder().iso3("VNM").iso2("VN").isoNumeric(704).usualName("Viêt Nam").officialName("VIET NAM").shortName("Viêt Nam").build();
    private Country Wallis_et_Futuna_WF= new Country().builder().iso3("WLF").iso2("WF").isoNumeric(876).usualName("Wallis-et-Futuna").officialName("WALLIS-ET-FUTUNA").shortName("Wallis-et-Futuna").build();
    private Country Yémen_YE= new Country().builder().iso3("YEM").iso2("YE").isoNumeric(887).usualName("Yémen").officialName("YÉMEN").shortName("Yémen").build();
    private Country Zambie_ZM= new Country().builder().iso3("ZMB").iso2("ZM").isoNumeric(894).usualName("Zambie").officialName("ZAMBIE").shortName("Zambie").build();
    private Country Zimbabwe_ZW= new Country().builder().iso3("ZWE").iso2("ZW").isoNumeric(716).usualName("Zimbabwe").officialName("ZIMBABWE").shortName("Zimbabwe").build();

  @Bean
  CommandLineRunner initDatabaseCountry(CountryRepository countryRepository, AreaRepository repository) {
    return args -> {
  	
    	countryRepository.save(Afghanistan_AF);
    	countryRepository.save(Afrique_du_Sud_ZA);
    	countryRepository.save(Îles_Åland_AX);
    	countryRepository.save(Albanie_AL);
    	countryRepository.save(Algérie_DZ);
    	countryRepository.save(Allemagne_DE);
    	countryRepository.save(Andorre_AD);
    	countryRepository.save(Angola_AO);
    	countryRepository.save(Anguilla_AI);
    	countryRepository.save(Antarctique_AQ);
    	countryRepository.save(Antigua_et_Barbuda_AG);
    	countryRepository.save(Arabie_saoudite_SA);
    	countryRepository.save(Argentine_AR);
    	countryRepository.save(Arménie_AM);
    	countryRepository.save(Aruba_AW);
    	countryRepository.save(Australie_AU);
    	countryRepository.save(Autriche_AT);
    	countryRepository.save(Azerbaïdjan_AZ);
    	countryRepository.save(Bahamas_BS);
    	countryRepository.save(Bahreïn_BH);
    	countryRepository.save(Bangladesh_BD);
    	countryRepository.save(Barbade_BB);
    	countryRepository.save(Biélorussie_BY);
    	countryRepository.save(Belgique_BE);
    	countryRepository.save(Belize_BZ);
    	countryRepository.save(Bénin_BJ);
    	countryRepository.save(Bermudes_BM);
    	countryRepository.save(Bhoutan_BT);
    	countryRepository.save(Bolivie_BO);
    	countryRepository.save(Pays_Bas_caribéens_BQ);
    	countryRepository.save(Bosnie_Herzégovine_BA);
    	countryRepository.save(Botswana_BW);
    	countryRepository.save(Île_Bouvet_BV);
    	countryRepository.save(Brésil_BR);
    	countryRepository.save(Brunei_BN);
    	countryRepository.save(Bulgarie_BG);
    	countryRepository.save(Burkina_Faso_BF);
    	countryRepository.save(Burundi_BI);
    	countryRepository.save(Îles_Caïmans_KY);
    	countryRepository.save(Cambodge_KH);
    	countryRepository.save(Cameroun_CM);
    	countryRepository.save(Canada_CA);
    	countryRepository.save(Cap_Vert_CV);
    	countryRepository.save(République_centrafricaine_CF);
    	countryRepository.save(Chili_CL);
    	countryRepository.save(Chine_CN);
    	countryRepository.save(Île_Christmas_CX);
    	countryRepository.save(Chypre__pays__CY);
    	countryRepository.save(Îles_Cocos_CC);
    	countryRepository.save(Colombie_CO);
    	countryRepository.save(Comores__pays__KM);
    	countryRepository.save(République_du_Congo_CG);
    	countryRepository.save(République_démocratique_du_Congo_CD);
    	countryRepository.save(Îles_Cook_CK);
    	countryRepository.save(Corée_du_Sud_KR);
    	countryRepository.save(Corée_du_Nord_KP);
    	countryRepository.save(Costa_Rica_CR);
    	countryRepository.save(Côte_d_Ivoire_CI);
    	countryRepository.save(Croatie_HR);
    	countryRepository.save(Cuba_CU);
    	countryRepository.save(Curaçao_CW);
    	countryRepository.save(Danemark_DK);
    	countryRepository.save(Djibouti_DJ);
    	countryRepository.save(République_dominicaine_DO);
    	countryRepository.save(Dominique_DM);
    	countryRepository.save(Égypte_EG);
    	countryRepository.save(Salvador_SV);
    	countryRepository.save(Émirats_arabes_unis_AE);
    	countryRepository.save(Équateur__pays__EC);
    	countryRepository.save(Érythrée_ER);
    	countryRepository.save(Espagne_ES);
    	countryRepository.save(Estonie_EE);
    	countryRepository.save(États_Unis_US);
    	countryRepository.save(Éthiopie_ET);
    	countryRepository.save(Malouines_FK);
    	countryRepository.save(Îles_Féroé_FO);
    	countryRepository.save(Fidji_FJ);
    	countryRepository.save(Finlande_FI);
    	countryRepository.save(France_FR);
    	countryRepository.save(Gabon_GA);
    	countryRepository.save(Gambie_GM);
    	countryRepository.save(Géorgie__pays__GE);
    	countryRepository.save(Géorgie_du_Sud_et_les_îles_Sandwich_du_Sud_GS);
    	countryRepository.save(Ghana_GH);
    	countryRepository.save(Gibraltar_GI);
    	countryRepository.save(Grèce_GR);
    	countryRepository.save(Grenade__pays__GD);
    	countryRepository.save(Groenland_GL);
    	countryRepository.save(Guadeloupe_GP);
    	countryRepository.save(Guam_GU);
    	countryRepository.save(Guatemala_GT);
    	countryRepository.save(Guernesey_GG);
    	countryRepository.save(Guinée_GN);
    	countryRepository.save(Guinée_Bissau_GW);
    	countryRepository.save(Guinée_équatoriale_GQ);
    	countryRepository.save(Guyana_GY);
    	countryRepository.save(Guyane_GF);
    	countryRepository.save(Haïti_HT);
    	countryRepository.save(Îles_Heard_et_MacDonald_HM);
    	countryRepository.save(Honduras_HN);
    	countryRepository.save(Hong_Kong_HK);
    	countryRepository.save(Hongrie_HU);
    	countryRepository.save(Île_de_Man_IM);
    	countryRepository.save(Îles_mineures_éloignées_des_États_Unis_UM);
    	countryRepository.save(Îles_Vierges_britanniques_VG);
    	countryRepository.save(Îles_Vierges_des_États_Unis_VI);
    	countryRepository.save(Inde_IN);
    	countryRepository.save(Indonésie_ID);
    	countryRepository.save(Iran_IR);
    	countryRepository.save(Irak_IQ);
    	countryRepository.save(Irlande__pays__IE);
    	countryRepository.save(Islande_IS);
    	countryRepository.save(Israël_IL);
    	countryRepository.save(Italie_IT);
    	countryRepository.save(Jamaïque_JM);
    	countryRepository.save(Japon_JP);
    	countryRepository.save(Jersey_JE);
    	countryRepository.save(Jordanie_JO);
    	countryRepository.save(Kazakhstan_KZ);
    	countryRepository.save(Kenya_KE);
    	countryRepository.save(Kirghizistan_KG);
    	countryRepository.save(Kiribati_KI);
    	countryRepository.save(Koweït_KW);
    	countryRepository.save(Laos_LA);
    	countryRepository.save(Lesotho_LS);
    	countryRepository.save(Lettonie_LV);
    	countryRepository.save(Liban_LB);
    	countryRepository.save(Liberia_LR);
    	countryRepository.save(Libye_LY);
    	countryRepository.save(Liechtenstein_LI);
    	countryRepository.save(Lituanie_LT);
    	countryRepository.save(Luxembourg__pays__LU);
    	countryRepository.save(Macao_MO);
    	countryRepository.save(Macédoine_du_Nord_MK);
    	countryRepository.save(Madagascar_MG);
    	countryRepository.save(Malaisie_MY);
    	countryRepository.save(Malawi_MW);
    	countryRepository.save(Maldives_MV);
    	countryRepository.save(Mali_ML);
    	countryRepository.save(Malte_MT);
    	countryRepository.save(Îles_Mariannes_du_Nord_MP);
    	countryRepository.save(Maroc_MA);
    	countryRepository.save(Îles_Marshall__pays__MH);
    	countryRepository.save(Martinique_MQ);
    	countryRepository.save(Maurice__pays__MU);
    	countryRepository.save(Mauritanie_MR);
    	countryRepository.save(Mayotte_YT);
    	countryRepository.save(Mexique_MX);
    	countryRepository.save(États_fédérés_de_Micronésie__pays__FM);
    	countryRepository.save(Moldavie_MD);
    	countryRepository.save(Monaco_MC);
    	countryRepository.save(Mongolie_MN);
    	countryRepository.save(Monténégro_ME);
    	countryRepository.save(Montserrat_MS);
    	countryRepository.save(Mozambique_MZ);
    	countryRepository.save(Birmanie_MM);
    	countryRepository.save(Namibie_NA);
    	countryRepository.save(Nauru_NR);
    	countryRepository.save(Népal_NP);
    	countryRepository.save(Nicaragua_NI);
    	countryRepository.save(Niger_NE);
    	countryRepository.save(Nigeria_NG);
    	countryRepository.save(Niue_NU);
    	countryRepository.save(Île_Norfolk_NF);
    	countryRepository.save(Norvège_NO);
    	countryRepository.save(Nouvelle_Calédonie_NC);
    	countryRepository.save(Nouvelle_Zélande_NZ);
    	countryRepository.save(Territoire_britannique_de_l_océan_Indien_IO);
    	countryRepository.save(Oman_OM);
    	countryRepository.save(Ouganda_UG);
    	countryRepository.save(Ouzbékistan_UZ);
    	countryRepository.save(Pakistan_PK);
    	countryRepository.save(Palaos_PW);
    	countryRepository.save(Palestine_PS);
    	countryRepository.save(Panama_PA);
    	countryRepository.save(Papouasie_Nouvelle_Guinée_PG);
    	countryRepository.save(Paraguay_PY);
    	countryRepository.save(Pays_Bas_NL);
    	countryRepository.save(Pérou_PE);
    	countryRepository.save(Philippines_PH);
    	countryRepository.save(Îles_Pitcairn_PN);
    	countryRepository.save(Pologne_PL);
    	countryRepository.save(Polynésie_française_PF);
    	countryRepository.save(Porto_Rico_PR);
    	countryRepository.save(Portugal_PT);
    	countryRepository.save(Qatar_QA);
    	countryRepository.save(La_Réunion_RE);
    	countryRepository.save(Roumanie_RO);
    	countryRepository.save(Royaume_Uni_GB);
    	countryRepository.save(Russie_RU);
    	countryRepository.save(Rwanda_RW);
    	countryRepository.save(République_arabe_sahraouie_démocratique_EH);
    	countryRepository.save(Saint_Barthélemy_BL);
    	countryRepository.save(Saint_Christophe_et_Niévès_KN);
    	countryRepository.save(Saint_Marin_SM);
    	countryRepository.save(Saint_Martin_MF);
    	countryRepository.save(Saint_Martin_SX);
    	countryRepository.save(Saint_Pierre_et_Miquelon_PM);
    	countryRepository.save(Saint_Siège__État_de_la_Cité_du_Vatican__VA);
    	countryRepository.save(Saint_Vincent_et_les_Grenadines_VC);
    	countryRepository.save(Sainte_Hélène_Ascension_et_Tristan_da_Cunha_SH);
    	countryRepository.save(Sainte_Lucie_LC);
    	countryRepository.save(Salomon_SB);
    	countryRepository.save(Samoa_WS);
    	countryRepository.save(Samoa_américaines_AS);
    	countryRepository.save(Sao_Tomé_et_Principe_ST);
    	countryRepository.save(Sénégal_SN);
    	countryRepository.save(Serbie_RS);
    	countryRepository.save(Seychelles_SC);
    	countryRepository.save(Sierra_Leone_SL);
    	countryRepository.save(Singapour_SG);
    	countryRepository.save(Slovaquie_SK);
    	countryRepository.save(Slovénie_SI);
    	countryRepository.save(Somalie_SO);
    	countryRepository.save(Soudan_SD);
    	countryRepository.save(Soudan_du_Sud_SS);
    	countryRepository.save(Sri_Lanka_LK);
    	countryRepository.save(Suède_SE);
    	countryRepository.save(Suisse_CH);
    	countryRepository.save(Suriname_SR);
    	countryRepository.save(Svalbard_et_ile_Jan_Mayen_SJ);
    	countryRepository.save(Swaziland_SZ);
    	countryRepository.save(Syrie_SY);
    	countryRepository.save(Tadjikistan_TJ);
    	countryRepository.save(Taïwan_République_de_Chine__Taïwan___TW);
    	countryRepository.save(Tanzanie_TZ);
    	countryRepository.save(Tchad_TD);
    	countryRepository.save(Tchéquie_CZ);
    	countryRepository.save(Terres_australes_et_antarctiques_françaises_TF);
    	countryRepository.save(Thaïlande_TH);
    	countryRepository.save(Timor_oriental_TL);
    	countryRepository.save(Togo_TG);
    	countryRepository.save(Tokelau_TK);
    	countryRepository.save(Tonga_TO);
    	countryRepository.save(Trinité_et_Tobago_TT);
    	countryRepository.save(Tunisie_TN);
    	countryRepository.save(Turkménistan_TM);
    	countryRepository.save(Îles_Turques_et_Caïques_TC);
    	countryRepository.save(Turquie_TR);
    	countryRepository.save(Tuvalu_TV);
    	countryRepository.save(Ukraine_UA);
    	countryRepository.save(Uruguay_UY);
    	countryRepository.save(Vanuatu_VU);
    	countryRepository.save(Venezuela_VE);
    	countryRepository.save(Viêt_Nam_VN);
    	countryRepository.save(Wallis_et_Futuna_WF);
    	countryRepository.save(Yémen_YE);
    	countryRepository.save(Zambie_ZM);
    	countryRepository.save(Zimbabwe_ZW);

      log.info("Preloading " + repository.save(new Area("AF", "Afrique", null)));
      log.info("Preloading " + repository.save(new Area("AFN", "Afrique du nord / Moyen-Orient", null)));
      log.info("Preloading " + repository.save(new Area("AM", "Amérique", null)));
      log.info("Preloading " + repository.save(new Area("ANT", "Antarctique", null)));
      log.info("Preloading " + repository.save(new Area("AS", "Asie-Océanie", null)));
      log.info("Preloading " + repository.save(new Area("EU", "Europe", this.countryList)));

    };
  }
}