server:
  port: 8081
  servlet: 
    context-path: /

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/MyRealm
          jwk-set-uri: http://localhost:8080/auth/realms/MyRealm/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate: ERROR
    fr.pontos3.rise.riserest: ERROR

         



